from enum import StrEnum


class Capability(StrEnum):
    TEXT_GENERATION = "TEXT_GENERATION"
    STRUCTURED_GENERATION = "STRUCTURED_GENERATION"
    IMAGE_GENERATION = "IMAGE_GENERATION"
    IMAGE_EDIT = "IMAGE_EDIT"
    VIDEO_GENERATION = "VIDEO_GENERATION"


class Operation(StrEnum):
    OFFER_CREATE_DRAFT = "OFFER_CREATE_DRAFT"
    OFFER_EDIT = "OFFER_EDIT"
    OFFER_FIELD_REWRITE = "OFFER_FIELD_REWRITE"
    CREATIVE_TEXT_GENERATION = "CREATIVE_TEXT_GENERATION"
    CREATIVE_SOCIAL_POST_GENERATION = "CREATIVE_SOCIAL_POST_GENERATION"
    CREATIVE_IMAGE_GENERATION = "CREATIVE_IMAGE_GENERATION"
    CREATIVE_TEXT_REWRITE = "CREATIVE_TEXT_REWRITE"
    PROMO_BRIEF_GENERATE = "PROMO_BRIEF_GENERATE"
    PROMO_TEXT_GENERATE = "PROMO_TEXT_GENERATE"
    PROMO_YANDEX_GENERATE = "PROMO_YANDEX_GENERATE"
    PROMO_IMAGE_PROMPT_GENERATE = "PROMO_IMAGE_PROMPT_GENERATE"
    PROMO_IMAGE_GENERATE = "PROMO_IMAGE_GENERATE"
    PROMO_QR_IMAGE_GENERATE = "PROMO_QR_IMAGE_GENERATE"


class EntityType(StrEnum):
    OFFER = "OFFER"
    CREATIVE = "CREATIVE"


TEXT_CAPABILITIES = {Capability.TEXT_GENERATION, Capability.STRUCTURED_GENERATION}
IMAGE_CAPABILITIES = {Capability.IMAGE_GENERATION}
UNIMPLEMENTED_CAPABILITIES = {
    Capability.IMAGE_EDIT,
    Capability.VIDEO_GENERATION,
}
