export type Vertical = {
  code: string;
  nameRu: string;
  nameEn: string;
};

export type Category = {
  code: string;
  verticalCode: string;
  nameRu: string;
  nameEn: string;
};

export const VERTICALS: Vertical[] = [
  { code: "FINANCE", nameRu: "Финансы", nameEn: "Finance" },
  { code: "INSURANCE", nameRu: "Страхование", nameEn: "Insurance" },
  { code: "CRYPTO_WEB3", nameRu: "Криптовалюты / Web3", nameEn: "Crypto / Web3" },
  { code: "RETAIL", nameRu: "Универсальный ритейл", nameEn: "Retail" },
  { code: "FASHION", nameRu: "Одежда и аксессуары", nameEn: "Fashion" },
  { code: "BEAUTY", nameRu: "Красота", nameEn: "Beauty" },
  { code: "ELECTRONICS", nameRu: "Электроника", nameEn: "Electronics" },
  { code: "HEALTH", nameRu: "Здоровье и медицина", nameEn: "Health" },
  { code: "NUTRA", nameRu: "Nutra / БАД", nameEn: "Nutra" },
  { code: "SPORTS_FITNESS", nameRu: "Спорт и фитнес", nameEn: "Sports & Fitness" },
  { code: "EDUCATION", nameRu: "Образование", nameEn: "Education" },
  { code: "HR_JOBS", nameRu: "Работа и HR", nameEn: "HR & Jobs" },
  { code: "SAAS", nameRu: "SaaS / горизонтальное ПО", nameEn: "SaaS" },
  { code: "CYBERSECURITY", nameRu: "Кибербезопасность", nameEn: "Cybersecurity" },
  { code: "HOSTING_INFRA", nameRu: "Хостинг и инфраструктура", nameEn: "Hosting & Infrastructure" },
  { code: "MARKETING_ADTECH", nameRu: "Маркетинг и AdTech", nameEn: "Marketing & AdTech" },
  { code: "B2B_SERVICES", nameRu: "Бизнес-услуги", nameEn: "B2B Services" },
  { code: "TELECOM", nameRu: "Телеком", nameEn: "Telecom" },
  { code: "GAMING", nameRu: "Игры", nameEn: "Gaming" },
  { code: "IGAMING", nameRu: "iGaming", nameEn: "iGaming" },
  { code: "DATING", nameRu: "Знакомства", nameEn: "Dating" },
  { code: "ADULT", nameRu: "Adult", nameEn: "Adult" },
  { code: "TRAVEL", nameRu: "Путешествия", nameEn: "Travel" },
  { code: "AUTOMOTIVE", nameRu: "Автомобили", nameEn: "Automotive" },
  { code: "REAL_ESTATE", nameRu: "Недвижимость", nameEn: "Real Estate" },
  { code: "HOME_FURNITURE", nameRu: "Дом и мебель", nameEn: "Home & Furniture" },
  { code: "CONSTRUCTION_REPAIR", nameRu: "Строительство и ремонт", nameEn: "Construction & Repair" },
  { code: "HOME_SERVICES", nameRu: "Бытовые услуги", nameEn: "Home Services" },
  { code: "ENERGY", nameRu: "Энергетика", nameEn: "Energy" },
  { code: "FOOD_GROCERY", nameRu: "Продукты", nameEn: "Food & Grocery" },
  { code: "RESTAURANTS_DELIVERY", nameRu: "Рестораны и готовая еда", nameEn: "Restaurants & Delivery" },
  { code: "LOGISTICS", nameRu: "Логистика", nameEn: "Logistics" },
  { code: "LEGAL", nameRu: "Юридические услуги", nameEn: "Legal" },
  { code: "IMMIGRATION_DOCUMENTS", nameRu: "Миграция и документы", nameEn: "Immigration & Documents" },
  { code: "MEDIA_ENTERTAINMENT", nameRu: "Медиа и развлечения", nameEn: "Media & Entertainment" },
  { code: "EVENTS_TICKETS", nameRu: "События и билеты", nameEn: "Events & Tickets" },
  { code: "PETS", nameRu: "Животные", nameEn: "Pets" },
  { code: "KIDS_FAMILY", nameRu: "Дети и семья", nameEn: "Kids & Family" },
  { code: "PHYSICAL_SECURITY", nameRu: "Физическая безопасность", nameEn: "Physical Security" },
  { code: "PRINT_PROMO", nameRu: "Полиграфия и промопродукция", nameEn: "Print & Promo" },
  { code: "INDUSTRIAL", nameRu: "Промышленность", nameEn: "Industrial" },
  { code: "AGRICULTURE", nameRu: "Сельское хозяйство", nameEn: "Agriculture" },
  { code: "SWEEPSTAKES_PROMOTIONS", nameRu: "Розыгрыши и промо", nameEn: "Sweepstakes & Promotions" },
  { code: "CHARITY", nameRu: "Благотворительность", nameEn: "Charity" },
  { code: "OTHER", nameRu: "Другое", nameEn: "Other" },
];

export const CATEGORIES: Category[] = [
  { code: "DEBIT_CARDS", verticalCode: "FINANCE", nameRu: "Дебетовые карты", nameEn: "Debit cards" },
  { code: "CREDIT_CARDS", verticalCode: "FINANCE", nameRu: "Кредитные карты", nameEn: "Credit cards" },
  { code: "INSTALLMENT_CARDS", verticalCode: "FINANCE", nameRu: "Карты рассрочки", nameEn: "Installment cards" },
  { code: "PERSONAL_BANK_ACCOUNTS", verticalCode: "FINANCE", nameRu: "Банковские счета физлиц", nameEn: "Personal bank accounts" },
  { code: "BUSINESS_BANK_ACCOUNTS", verticalCode: "FINANCE", nameRu: "Расчётные счета бизнеса", nameEn: "Business bank accounts" },
  { code: "CASH_MANAGEMENT", verticalCode: "FINANCE", nameRu: "РКО", nameEn: "Cash management" },
  { code: "ACQUIRING", verticalCode: "FINANCE", nameRu: "Эквайринг", nameEn: "Acquiring" },
  { code: "CONSUMER_LOANS", verticalCode: "FINANCE", nameRu: "Потребительские кредиты", nameEn: "Consumer loans" },
  { code: "CASH_LOANS", verticalCode: "FINANCE", nameRu: "Кредиты наличными", nameEn: "Cash loans" },
  { code: "AUTO_LOANS", verticalCode: "FINANCE", nameRu: "Автокредиты", nameEn: "Auto loans" },
  { code: "MORTGAGE", verticalCode: "FINANCE", nameRu: "Ипотека", nameEn: "Mortgage" },
  { code: "REFINANCING", verticalCode: "FINANCE", nameRu: "Рефинансирование", nameEn: "Refinancing" },
  { code: "MICROLOANS", verticalCode: "FINANCE", nameRu: "Микрозаймы", nameEn: "Microloans" },
  { code: "BNPL", verticalCode: "FINANCE", nameRu: "BNPL / оплата частями", nameEn: "BNPL" },
  { code: "INSTALLMENT_FINANCE", verticalCode: "FINANCE", nameRu: "Финансовая рассрочка", nameEn: "Installment finance" },
  { code: "DEPOSITS", verticalCode: "FINANCE", nameRu: "Вклады", nameEn: "Deposits" },
  { code: "SAVINGS_ACCOUNTS", verticalCode: "FINANCE", nameRu: "Накопительные счета", nameEn: "Savings accounts" },
  { code: "BROKERAGE", verticalCode: "FINANCE", nameRu: "Брокерские услуги", nameEn: "Brokerage" },
  { code: "INVESTMENT_ACCOUNTS", verticalCode: "FINANCE", nameRu: "Инвестиционные счета", nameEn: "Investment accounts" },
  { code: "ASSET_MANAGEMENT", verticalCode: "FINANCE", nameRu: "Управление активами", nameEn: "Asset management" },
  { code: "ROBO_ADVISORY", verticalCode: "FINANCE", nameRu: "Робоэдвайзинг", nameEn: "Robo-advisory" },
  { code: "FOREX", verticalCode: "FINANCE", nameRu: "Forex", nameEn: "Forex" },
  { code: "MONEY_TRANSFERS", verticalCode: "FINANCE", nameRu: "Денежные переводы", nameEn: "Money transfers" },
  { code: "PAYMENT_SERVICES", verticalCode: "FINANCE", nameRu: "Платёжные сервисы", nameEn: "Payment services" },
  { code: "E_WALLETS", verticalCode: "FINANCE", nameRu: "Электронные кошельки", nameEn: "E-wallets" },
  { code: "BUSINESS_LOANS", verticalCode: "FINANCE", nameRu: "Кредиты бизнесу", nameEn: "Business loans" },
  { code: "FACTORING", verticalCode: "FINANCE", nameRu: "Факторинг", nameEn: "Factoring" },
  { code: "LEASING", verticalCode: "FINANCE", nameRu: "Лизинг", nameEn: "Leasing" },
  { code: "CROWDLENDING", verticalCode: "FINANCE", nameRu: "Краудлендинг", nameEn: "Crowdlending" },
  { code: "INVESTMENT_CROWDFUNDING", verticalCode: "FINANCE", nameRu: "Инвестиционный краудфандинг", nameEn: "Investment crowdfunding" },
  { code: "CREDIT_HISTORY", verticalCode: "FINANCE", nameRu: "Кредитные истории", nameEn: "Credit history" },
  { code: "DEBT_RESTRUCTURING", verticalCode: "FINANCE", nameRu: "Реструктуризация задолженности", nameEn: "Debt restructuring" },
  { code: "OSAGO", verticalCode: "INSURANCE", nameRu: "ОСАГО", nameEn: "OSAGO" },
  { code: "CASCO", verticalCode: "INSURANCE", nameRu: "КАСКО", nameEn: "CASCO" },
  { code: "LIFE_INSURANCE", verticalCode: "INSURANCE", nameRu: "Страхование жизни", nameEn: "Life insurance" },
  { code: "HEALTH_INSURANCE", verticalCode: "INSURANCE", nameRu: "Медицинское страхование", nameEn: "Health insurance" },
  { code: "DMS", verticalCode: "INSURANCE", nameRu: "ДМС", nameEn: "Voluntary health insurance" },
  { code: "TRAVEL_INSURANCE", verticalCode: "INSURANCE", nameRu: "Страхование путешествий", nameEn: "Travel insurance" },
  { code: "PROPERTY_INSURANCE", verticalCode: "INSURANCE", nameRu: "Страхование имущества", nameEn: "Property insurance" },
  { code: "HOME_INSURANCE", verticalCode: "INSURANCE", nameRu: "Страхование жилья", nameEn: "Home insurance" },
  { code: "ACCIDENT_INSURANCE", verticalCode: "INSURANCE", nameRu: "Страхование от несчастных случаев", nameEn: "Accident insurance" },
  { code: "LIABILITY_INSURANCE", verticalCode: "INSURANCE", nameRu: "Страхование ответственности", nameEn: "Liability insurance" },
  { code: "BUSINESS_INSURANCE", verticalCode: "INSURANCE", nameRu: "Страхование бизнеса", nameEn: "Business insurance" },
  { code: "PET_INSURANCE", verticalCode: "INSURANCE", nameRu: "Страхование животных", nameEn: "Pet insurance" },
  { code: "DEVICE_INSURANCE", verticalCode: "INSURANCE", nameRu: "Страхование техники", nameEn: "Device insurance" },
  { code: "CYBER_INSURANCE", verticalCode: "INSURANCE", nameRu: "Киберстрахование", nameEn: "Cyber insurance" },
  { code: "MORTGAGE_INSURANCE", verticalCode: "INSURANCE", nameRu: "Ипотечное страхование", nameEn: "Mortgage insurance" },
  { code: "CRYPTO_EXCHANGES", verticalCode: "CRYPTO_WEB3", nameRu: "Криптобиржи", nameEn: "Crypto exchanges" },
  { code: "CRYPTO_WALLETS", verticalCode: "CRYPTO_WEB3", nameRu: "Криптокошельки", nameEn: "Crypto wallets" },
  { code: "CRYPTO_PAYMENTS", verticalCode: "CRYPTO_WEB3", nameRu: "Криптоплатежи", nameEn: "Crypto payments" },
  { code: "CRYPTO_CARDS", verticalCode: "CRYPTO_WEB3", nameRu: "Криптокарты", nameEn: "Crypto cards" },
  { code: "DEFI", verticalCode: "CRYPTO_WEB3", nameRu: "DeFi", nameEn: "DeFi" },
  { code: "STAKING", verticalCode: "CRYPTO_WEB3", nameRu: "Стейкинг", nameEn: "Staking" },
  { code: "CRYPTO_LENDING", verticalCode: "CRYPTO_WEB3", nameRu: "Криптокредитование", nameEn: "Crypto lending" },
  { code: "CRYPTO_TRADING", verticalCode: "CRYPTO_WEB3", nameRu: "Криптотрейдинг", nameEn: "Crypto trading" },
  { code: "CRYPTO_ANALYTICS", verticalCode: "CRYPTO_WEB3", nameRu: "Криптоаналитика", nameEn: "Crypto analytics" },
  { code: "NFT_PLATFORMS", verticalCode: "CRYPTO_WEB3", nameRu: "NFT-платформы", nameEn: "NFT platforms" },
  { code: "MINING_SERVICES", verticalCode: "CRYPTO_WEB3", nameRu: "Майнинг", nameEn: "Mining" },
  { code: "BLOCKCHAIN_INFRASTRUCTURE", verticalCode: "CRYPTO_WEB3", nameRu: "Blockchain-инфраструктура", nameEn: "Blockchain infrastructure" },
  { code: "WEB3_APPS", verticalCode: "CRYPTO_WEB3", nameRu: "Web3-приложения", nameEn: "Web3 apps" },
  { code: "GENERAL_ONLINE_STORES", verticalCode: "RETAIL", nameRu: "Универсальные интернет-магазины", nameEn: "General online stores" },
  { code: "GENERAL_MARKETPLACES", verticalCode: "RETAIL", nameRu: "Маркетплейсы", nameEn: "Marketplaces" },
  { code: "GIFTS", verticalCode: "RETAIL", nameRu: "Подарки", nameEn: "Gifts" },
  { code: "HOBBY_CRAFTS", verticalCode: "RETAIL", nameRu: "Хобби и рукоделие", nameEn: "Hobby & crafts" },
  { code: "COLLECTIBLES", verticalCode: "RETAIL", nameRu: "Коллекционирование", nameEn: "Collectibles" },
  { code: "LUXURY_GOODS", verticalCode: "RETAIL", nameRu: "Товары класса люкс", nameEn: "Luxury goods" },
  { code: "SECOND_HAND", verticalCode: "RETAIL", nameRu: "Секонд-хенд", nameEn: "Second-hand" },
  { code: "REFURBISHED_GOODS", verticalCode: "RETAIL", nameRu: "Восстановленные товары", nameEn: "Refurbished goods" },
  { code: "OFFICE_SUPPLIES", verticalCode: "RETAIL", nameRu: "Канцелярия", nameEn: "Office supplies" },
  { code: "FLOWERS", verticalCode: "RETAIL", nameRu: "Цветы", nameEn: "Flowers" },
  { code: "WOMENS_CLOTHING", verticalCode: "FASHION", nameRu: "Женская одежда", nameEn: "Women's clothing" },
  { code: "MENS_CLOTHING", verticalCode: "FASHION", nameRu: "Мужская одежда", nameEn: "Men's clothing" },
  { code: "FOOTWEAR", verticalCode: "FASHION", nameRu: "Обувь", nameEn: "Footwear" },
  { code: "SPORTSWEAR", verticalCode: "FASHION", nameRu: "Спортивная одежда", nameEn: "Sportswear" },
  { code: "UNDERWEAR", verticalCode: "FASHION", nameRu: "Бельё", nameEn: "Underwear" },
  { code: "BAGS", verticalCode: "FASHION", nameRu: "Сумки", nameEn: "Bags" },
  { code: "FASHION_ACCESSORIES", verticalCode: "FASHION", nameRu: "Модные аксессуары", nameEn: "Fashion accessories" },
  { code: "JEWELRY", verticalCode: "FASHION", nameRu: "Ювелирные изделия", nameEn: "Jewelry" },
  { code: "WATCHES", verticalCode: "FASHION", nameRu: "Часы", nameEn: "Watches" },
  { code: "EYEWEAR", verticalCode: "FASHION", nameRu: "Очки", nameEn: "Eyewear" },
  { code: "STREETWEAR", verticalCode: "FASHION", nameRu: "Стритвир", nameEn: "Streetwear" },
  { code: "WORKWEAR", verticalCode: "FASHION", nameRu: "Спецодежда", nameEn: "Workwear" },
  { code: "COSMETICS", verticalCode: "BEAUTY", nameRu: "Косметика", nameEn: "Cosmetics" },
  { code: "PERFUMERY", verticalCode: "BEAUTY", nameRu: "Парфюмерия", nameEn: "Perfumery" },
  { code: "SKINCARE", verticalCode: "BEAUTY", nameRu: "Уход за кожей", nameEn: "Skincare" },
  { code: "BODY_CARE", verticalCode: "BEAUTY", nameRu: "Уход за телом", nameEn: "Body care" },
  { code: "HAIR_CARE", verticalCode: "BEAUTY", nameRu: "Уход за волосами", nameEn: "Hair care" },
  { code: "PROFESSIONAL_COSMETICS", verticalCode: "BEAUTY", nameRu: "Профессиональная косметика", nameEn: "Professional cosmetics" },
  { code: "BEAUTY_DEVICES", verticalCode: "BEAUTY", nameRu: "Приборы для красоты", nameEn: "Beauty devices" },
  { code: "BEAUTY_SALONS", verticalCode: "BEAUTY", nameRu: "Салоны красоты", nameEn: "Beauty salons" },
  { code: "COSMETOLOGY", verticalCode: "BEAUTY", nameRu: "Косметология", nameEn: "Cosmetology" },
  { code: "NAIL_SERVICES", verticalCode: "BEAUTY", nameRu: "Ногтевой сервис", nameEn: "Nail services" },
  { code: "BARBER_SERVICES", verticalCode: "BEAUTY", nameRu: "Барбершопы", nameEn: "Barber services" },
  { code: "SMARTPHONES", verticalCode: "ELECTRONICS", nameRu: "Смартфоны", nameEn: "Smartphones" },
  { code: "LAPTOPS", verticalCode: "ELECTRONICS", nameRu: "Ноутбуки", nameEn: "Laptops" },
  { code: "DESKTOP_COMPUTERS", verticalCode: "ELECTRONICS", nameRu: "Настольные компьютеры", nameEn: "Desktop computers" },
  { code: "PC_COMPONENTS", verticalCode: "ELECTRONICS", nameRu: "Комплектующие", nameEn: "PC components" },
  { code: "TABLETS", verticalCode: "ELECTRONICS", nameRu: "Планшеты", nameEn: "Tablets" },
  { code: "TV", verticalCode: "ELECTRONICS", nameRu: "Телевизоры", nameEn: "TVs" },
  { code: "AUDIO_EQUIPMENT", verticalCode: "ELECTRONICS", nameRu: "Аудиотехника", nameEn: "Audio equipment" },
  { code: "HEADPHONES", verticalCode: "ELECTRONICS", nameRu: "Наушники", nameEn: "Headphones" },
  { code: "CAMERAS", verticalCode: "ELECTRONICS", nameRu: "Фото- и видеокамеры", nameEn: "Cameras" },
  { code: "WEARABLES", verticalCode: "ELECTRONICS", nameRu: "Носимая электроника", nameEn: "Wearables" },
  { code: "GAMING_HARDWARE", verticalCode: "ELECTRONICS", nameRu: "Игровое железо", nameEn: "Gaming hardware" },
  { code: "DRONES", verticalCode: "ELECTRONICS", nameRu: "Дроны", nameEn: "Drones" },
  { code: "ELECTRONIC_ACCESSORIES", verticalCode: "ELECTRONICS", nameRu: "Электронные аксессуары", nameEn: "Electronic accessories" },
  { code: "CLINICS", verticalCode: "HEALTH", nameRu: "Клиники", nameEn: "Clinics" },
  { code: "MEDICAL_CENTERS", verticalCode: "HEALTH", nameRu: "Медицинские центры", nameEn: "Medical centers" },
  { code: "TELEMEDICINE", verticalCode: "HEALTH", nameRu: "Телемедицина", nameEn: "Telemedicine" },
  { code: "DIAGNOSTICS", verticalCode: "HEALTH", nameRu: "Диагностика", nameEn: "Diagnostics" },
  { code: "LAB_TESTS", verticalCode: "HEALTH", nameRu: "Лабораторные анализы", nameEn: "Lab tests" },
  { code: "DENTISTRY", verticalCode: "HEALTH", nameRu: "Стоматология", nameEn: "Dentistry" },
  { code: "OPHTHALMOLOGY", verticalCode: "HEALTH", nameRu: "Офтальмология", nameEn: "Ophthalmology" },
  { code: "REPRODUCTIVE_MEDICINE", verticalCode: "HEALTH", nameRu: "Репродуктивная медицина", nameEn: "Reproductive medicine" },
  { code: "PHYSIOTHERAPY", verticalCode: "HEALTH", nameRu: "Физиотерапия", nameEn: "Physiotherapy" },
  { code: "REHABILITATION", verticalCode: "HEALTH", nameRu: "Реабилитация", nameEn: "Rehabilitation" },
  { code: "MENTAL_HEALTH", verticalCode: "HEALTH", nameRu: "Ментальное здоровье", nameEn: "Mental health" },
  { code: "PHARMACIES", verticalCode: "HEALTH", nameRu: "Аптеки", nameEn: "Pharmacies" },
  { code: "MEDICAL_EQUIPMENT", verticalCode: "HEALTH", nameRu: "Медицинское оборудование", nameEn: "Medical equipment" },
  { code: "MEDICAL_CHECKUPS", verticalCode: "HEALTH", nameRu: "Чекапы", nameEn: "Medical checkups" },
  { code: "VITAMINS", verticalCode: "NUTRA", nameRu: "Витамины", nameEn: "Vitamins" },
  { code: "MINERALS", verticalCode: "NUTRA", nameRu: "Минералы", nameEn: "Minerals" },
  { code: "DIETARY_SUPPLEMENTS", verticalCode: "NUTRA", nameRu: "БАД", nameEn: "Dietary supplements" },
  { code: "SPORTS_SUPPLEMENTS", verticalCode: "NUTRA", nameRu: "Спортивное питание", nameEn: "Sports supplements" },
  { code: "PROTEIN", verticalCode: "NUTRA", nameRu: "Протеин", nameEn: "Protein" },
  { code: "JOINT_SUPPLEMENTS", verticalCode: "NUTRA", nameRu: "Для суставов", nameEn: "Joint supplements" },
  { code: "SLEEP_SUPPLEMENTS", verticalCode: "NUTRA", nameRu: "Для сна", nameEn: "Sleep supplements" },
  { code: "IMMUNITY_SUPPLEMENTS", verticalCode: "NUTRA", nameRu: "Для иммунитета", nameEn: "Immunity supplements" },
  { code: "DIGESTION_SUPPLEMENTS", verticalCode: "NUTRA", nameRu: "Для пищеварения", nameEn: "Digestion supplements" },
  { code: "BEAUTY_SUPPLEMENTS", verticalCode: "NUTRA", nameRu: "Для красоты", nameEn: "Beauty supplements" },
  { code: "WEIGHT_MANAGEMENT", verticalCode: "NUTRA", nameRu: "Контроль веса", nameEn: "Weight management" },
  { code: "MENS_SUPPLEMENTS", verticalCode: "NUTRA", nameRu: "Для мужчин", nameEn: "Men's supplements" },
  { code: "WOMENS_SUPPLEMENTS", verticalCode: "NUTRA", nameRu: "Для женщин", nameEn: "Women's supplements" },
  { code: "HERBAL_PRODUCTS", verticalCode: "NUTRA", nameRu: "Растительные препараты", nameEn: "Herbal products" },
  { code: "FITNESS_CLUBS", verticalCode: "SPORTS_FITNESS", nameRu: "Фитнес-клубы", nameEn: "Fitness clubs" },
  { code: "ONLINE_FITNESS", verticalCode: "SPORTS_FITNESS", nameRu: "Онлайн-фитнес", nameEn: "Online fitness" },
  { code: "PERSONAL_TRAINING", verticalCode: "SPORTS_FITNESS", nameRu: "Персональные тренировки", nameEn: "Personal training" },
  { code: "YOGA", verticalCode: "SPORTS_FITNESS", nameRu: "Йога", nameEn: "Yoga" },
  { code: "PILATES", verticalCode: "SPORTS_FITNESS", nameRu: "Пилатес", nameEn: "Pilates" },
  { code: "RUNNING_SERVICES", verticalCode: "SPORTS_FITNESS", nameRu: "Бег", nameEn: "Running" },
  { code: "CYCLING_SERVICES", verticalCode: "SPORTS_FITNESS", nameRu: "Велоспорт", nameEn: "Cycling" },
  { code: "SWIMMING_SERVICES", verticalCode: "SPORTS_FITNESS", nameRu: "Плавание", nameEn: "Swimming" },
  { code: "COMBAT_SPORTS", verticalCode: "SPORTS_FITNESS", nameRu: "Единоборства", nameEn: "Combat sports" },
  { code: "FITNESS_APPS", verticalCode: "SPORTS_FITNESS", nameRu: "Фитнес-приложения", nameEn: "Fitness apps" },
  { code: "FITNESS_EQUIPMENT", verticalCode: "SPORTS_FITNESS", nameRu: "Фитнес-оборудование", nameEn: "Fitness equipment" },
  { code: "SPORTING_GOODS", verticalCode: "SPORTS_FITNESS", nameRu: "Спортивные товары", nameEn: "Sporting goods" },
  { code: "ONLINE_COURSES", verticalCode: "EDUCATION", nameRu: "Онлайн-курсы", nameEn: "Online courses" },
  { code: "VOCATIONAL_EDUCATION", verticalCode: "EDUCATION", nameRu: "Профессиональное образование", nameEn: "Vocational education" },
  { code: "HIGHER_EDUCATION", verticalCode: "EDUCATION", nameRu: "Высшее образование", nameEn: "Higher education" },
  { code: "COLLEGES", verticalCode: "EDUCATION", nameRu: "Колледжи", nameEn: "Colleges" },
  { code: "SCHOOLS", verticalCode: "EDUCATION", nameRu: "Школы", nameEn: "Schools" },
  { code: "PROGRAMMING_EDUCATION", verticalCode: "EDUCATION", nameRu: "Обучение программированию", nameEn: "Programming education" },
  { code: "DATA_SCIENCE_EDUCATION", verticalCode: "EDUCATION", nameRu: "Data Science", nameEn: "Data science education" },
  { code: "AI_EDUCATION", verticalCode: "EDUCATION", nameRu: "Обучение AI", nameEn: "AI education" },
  { code: "DESIGN_EDUCATION", verticalCode: "EDUCATION", nameRu: "Дизайн", nameEn: "Design education" },
  { code: "MARKETING_EDUCATION", verticalCode: "EDUCATION", nameRu: "Маркетинг", nameEn: "Marketing education" },
  { code: "MANAGEMENT_EDUCATION", verticalCode: "EDUCATION", nameRu: "Менеджмент", nameEn: "Management education" },
  { code: "SALES_EDUCATION", verticalCode: "EDUCATION", nameRu: "Продажи", nameEn: "Sales education" },
  { code: "FINANCE_EDUCATION", verticalCode: "EDUCATION", nameRu: "Финансы", nameEn: "Finance education" },
  { code: "LANGUAGE_COURSES", verticalCode: "EDUCATION", nameRu: "Языковые курсы", nameEn: "Language courses" },
  { code: "ENGLISH_COURSES", verticalCode: "EDUCATION", nameRu: "Английский язык", nameEn: "English courses" },
  { code: "TUTORING", verticalCode: "EDUCATION", nameRu: "Репетиторство", nameEn: "Tutoring" },
  { code: "EXAM_PREPARATION", verticalCode: "EDUCATION", nameRu: "Подготовка к экзаменам", nameEn: "Exam preparation" },
  { code: "CHILDRENS_EDUCATION", verticalCode: "EDUCATION", nameRu: "Детское образование", nameEn: "Children's education" },
  { code: "CORPORATE_EDUCATION", verticalCode: "EDUCATION", nameRu: "Корпоративное обучение", nameEn: "Corporate education" },
  { code: "PROFESSIONAL_CERTIFICATION", verticalCode: "EDUCATION", nameRu: "Профессиональная сертификация", nameEn: "Professional certification" },
  { code: "SOFT_SKILLS_EDUCATION", verticalCode: "EDUCATION", nameRu: "Soft skills", nameEn: "Soft skills education" },
  { code: "MBA", verticalCode: "EDUCATION", nameRu: "MBA", nameEn: "MBA" },
  { code: "MUSIC_EDUCATION", verticalCode: "EDUCATION", nameRu: "Музыкальное образование", nameEn: "Music education" },
  { code: "CREATIVE_EDUCATION", verticalCode: "EDUCATION", nameRu: "Творческое образование", nameEn: "Creative education" },
  { code: "JOB_BOARDS", verticalCode: "HR_JOBS", nameRu: "Доски вакансий", nameEn: "Job boards" },
  { code: "RECRUITMENT", verticalCode: "HR_JOBS", nameRu: "Рекрутинг", nameEn: "Recruitment" },
  { code: "EXECUTIVE_SEARCH", verticalCode: "HR_JOBS", nameRu: "Executive search", nameEn: "Executive search" },
  { code: "STAFFING", verticalCode: "HR_JOBS", nameRu: "Аутстаффинг", nameEn: "Staffing" },
  { code: "FREELANCE_PLATFORMS", verticalCode: "HR_JOBS", nameRu: "Фриланс-платформы", nameEn: "Freelance platforms" },
  { code: "GIG_WORK", verticalCode: "HR_JOBS", nameRu: "Гиг-работа", nameEn: "Gig work" },
  { code: "INTERNSHIPS", verticalCode: "HR_JOBS", nameRu: "Стажировки", nameEn: "Internships" },
  { code: "CAREER_COACHING", verticalCode: "HR_JOBS", nameRu: "Карьерный коучинг", nameEn: "Career coaching" },
  { code: "RESUME_SERVICES", verticalCode: "HR_JOBS", nameRu: "Резюме", nameEn: "Resume services" },
  { code: "ATS", verticalCode: "HR_JOBS", nameRu: "ATS", nameEn: "ATS" },
  { code: "HRM", verticalCode: "HR_JOBS", nameRu: "HRM", nameEn: "HRM" },
  { code: "PAYROLL_HR", verticalCode: "HR_JOBS", nameRu: "Кадровый учёт и зарплата", nameEn: "Payroll HR" },
  { code: "EMPLOYEE_BENEFITS", verticalCode: "HR_JOBS", nameRu: "Льготы сотрудникам", nameEn: "Employee benefits" },
  { code: "ASSESSMENT_SERVICES", verticalCode: "HR_JOBS", nameRu: "Оценка персонала", nameEn: "Assessment services" },
  { code: "BACKGROUND_CHECKS", verticalCode: "HR_JOBS", nameRu: "Проверки кандидатов", nameEn: "Background checks" },
  { code: "CRM", verticalCode: "SAAS", nameRu: "CRM", nameEn: "CRM" },
  { code: "ERP", verticalCode: "SAAS", nameRu: "ERP", nameEn: "ERP" },
  { code: "PROJECT_MANAGEMENT", verticalCode: "SAAS", nameRu: "Управление проектами", nameEn: "Project management" },
  { code: "TASK_MANAGEMENT", verticalCode: "SAAS", nameRu: "Управление задачами", nameEn: "Task management" },
  { code: "COLLABORATION_SOFTWARE", verticalCode: "SAAS", nameRu: "Совместная работа", nameEn: "Collaboration software" },
  { code: "VIDEO_CONFERENCING", verticalCode: "SAAS", nameRu: "Видеоконференции", nameEn: "Video conferencing" },
  { code: "HELPDESK", verticalCode: "SAAS", nameRu: "Helpdesk", nameEn: "Helpdesk" },
  { code: "CUSTOMER_SUCCESS_SOFTWARE", verticalCode: "SAAS", nameRu: "Customer success", nameEn: "Customer success software" },
  { code: "ACCOUNTING_SOFTWARE", verticalCode: "SAAS", nameRu: "Бухгалтерия", nameEn: "Accounting software" },
  { code: "SALES_SOFTWARE", verticalCode: "SAAS", nameRu: "Продажи", nameEn: "Sales software" },
  { code: "BUSINESS_ANALYTICS", verticalCode: "SAAS", nameRu: "Бизнес-аналитика", nameEn: "Business analytics" },
  { code: "AI_TOOLS", verticalCode: "SAAS", nameRu: "AI-инструменты", nameEn: "AI tools" },
  { code: "GENERATIVE_AI", verticalCode: "SAAS", nameRu: "Генеративный AI", nameEn: "Generative AI" },
  { code: "DEVELOPER_TOOLS", verticalCode: "SAAS", nameRu: "Инструменты разработчика", nameEn: "Developer tools" },
  { code: "IDE_TOOLS", verticalCode: "SAAS", nameRu: "IDE", nameEn: "IDE tools" },
  { code: "API_PLATFORMS", verticalCode: "SAAS", nameRu: "API-платформы", nameEn: "API platforms" },
  { code: "NO_CODE", verticalCode: "SAAS", nameRu: "No-code", nameEn: "No-code" },
  { code: "LOW_CODE", verticalCode: "SAAS", nameRu: "Low-code", nameEn: "Low-code" },
  { code: "DOCUMENT_MANAGEMENT", verticalCode: "SAAS", nameRu: "Документооборот", nameEn: "Document management" },
  { code: "E_SIGNATURE", verticalCode: "SAAS", nameRu: "Электронная подпись", nameEn: "E-signature" },
  { code: "PRODUCTIVITY_SOFTWARE", verticalCode: "SAAS", nameRu: "Продуктивность", nameEn: "Productivity software" },
  { code: "OFFICE_SOFTWARE", verticalCode: "SAAS", nameRu: "Офисное ПО", nameEn: "Office software" },
  { code: "WEBSITE_BUILDERS", verticalCode: "SAAS", nameRu: "Конструкторы сайтов", nameEn: "Website builders" },
  { code: "CMS", verticalCode: "SAAS", nameRu: "CMS", nameEn: "CMS" },
  { code: "ECOMMERCE_PLATFORMS", verticalCode: "SAAS", nameRu: "E-commerce платформы", nameEn: "Ecommerce platforms" },
  { code: "DESIGN_SOFTWARE", verticalCode: "SAAS", nameRu: "Дизайн", nameEn: "Design software" },
  { code: "VIDEO_SOFTWARE", verticalCode: "SAAS", nameRu: "Видео", nameEn: "Video software" },
  { code: "AUDIO_SOFTWARE", verticalCode: "SAAS", nameRu: "Аудио", nameEn: "Audio software" },
  { code: "ANTIVIRUS", verticalCode: "CYBERSECURITY", nameRu: "Антивирусы", nameEn: "Antivirus" },
  { code: "ENDPOINT_PROTECTION", verticalCode: "CYBERSECURITY", nameRu: "Защита конечных точек", nameEn: "Endpoint protection" },
  { code: "VPN", verticalCode: "CYBERSECURITY", nameRu: "VPN", nameEn: "VPN" },
  { code: "PASSWORD_MANAGERS", verticalCode: "CYBERSECURITY", nameRu: "Менеджеры паролей", nameEn: "Password managers" },
  { code: "DLP", verticalCode: "CYBERSECURITY", nameRu: "DLP", nameEn: "DLP" },
  { code: "SIEM", verticalCode: "CYBERSECURITY", nameRu: "SIEM", nameEn: "SIEM" },
  { code: "SOC_SERVICES", verticalCode: "CYBERSECURITY", nameRu: "SOC", nameEn: "SOC services" },
  { code: "VULNERABILITY_MANAGEMENT", verticalCode: "CYBERSECURITY", nameRu: "Управление уязвимостями", nameEn: "Vulnerability management" },
  { code: "PENETRATION_TESTING", verticalCode: "CYBERSECURITY", nameRu: "Пентесты", nameEn: "Penetration testing" },
  { code: "CLOUD_SECURITY", verticalCode: "CYBERSECURITY", nameRu: "Облачная безопасность", nameEn: "Cloud security" },
  { code: "EMAIL_SECURITY", verticalCode: "CYBERSECURITY", nameRu: "Безопасность почты", nameEn: "Email security" },
  { code: "ANTI_FRAUD", verticalCode: "CYBERSECURITY", nameRu: "Антифрод", nameEn: "Anti-fraud" },
  { code: "IDENTITY_VERIFICATION", verticalCode: "CYBERSECURITY", nameRu: "Верификация личности", nameEn: "Identity verification" },
  { code: "KYC_SERVICES", verticalCode: "CYBERSECURITY", nameRu: "KYC", nameEn: "KYC services" },
  { code: "CYBERSECURITY_TRAINING", verticalCode: "CYBERSECURITY", nameRu: "Обучение кибербезопасности", nameEn: "Cybersecurity training" },
  { code: "WEB_HOSTING", verticalCode: "HOSTING_INFRA", nameRu: "Веб-хостинг", nameEn: "Web hosting" },
  { code: "VPS_VDS", verticalCode: "HOSTING_INFRA", nameRu: "VPS/VDS", nameEn: "VPS/VDS" },
  { code: "DEDICATED_SERVERS", verticalCode: "HOSTING_INFRA", nameRu: "Выделенные серверы", nameEn: "Dedicated servers" },
  { code: "CLOUD_COMPUTE", verticalCode: "HOSTING_INFRA", nameRu: "Облачные вычисления", nameEn: "Cloud compute" },
  { code: "KUBERNETES_HOSTING", verticalCode: "HOSTING_INFRA", nameRu: "Kubernetes-хостинг", nameEn: "Kubernetes hosting" },
  { code: "DOMAINS", verticalCode: "HOSTING_INFRA", nameRu: "Домены", nameEn: "Domains" },
  { code: "SSL_CERTIFICATES", verticalCode: "HOSTING_INFRA", nameRu: "SSL-сертификаты", nameEn: "SSL certificates" },
  { code: "CDN", verticalCode: "HOSTING_INFRA", nameRu: "CDN", nameEn: "CDN" },
  { code: "DNS_SERVICES", verticalCode: "HOSTING_INFRA", nameRu: "DNS", nameEn: "DNS services" },
  { code: "OBJECT_STORAGE", verticalCode: "HOSTING_INFRA", nameRu: "Объектное хранилище", nameEn: "Object storage" },
  { code: "BACKUP_SERVICES", verticalCode: "HOSTING_INFRA", nameRu: "Резервное копирование", nameEn: "Backup services" },
  { code: "COLOCATION", verticalCode: "HOSTING_INFRA", nameRu: "Колокация", nameEn: "Colocation" },
  { code: "MANAGED_INFRASTRUCTURE", verticalCode: "HOSTING_INFRA", nameRu: "Управляемая инфраструктура", nameEn: "Managed infrastructure" },
  { code: "DATABASE_HOSTING", verticalCode: "HOSTING_INFRA", nameRu: "Хостинг баз данных", nameEn: "Database hosting" },
  { code: "EMAIL_HOSTING", verticalCode: "HOSTING_INFRA", nameRu: "Почтовый хостинг", nameEn: "Email hosting" },
  { code: "CONTEXTUAL_ADVERTISING_SERVICES", verticalCode: "MARKETING_ADTECH", nameRu: "Контекстная реклама", nameEn: "Contextual advertising" },
  { code: "TARGETED_ADVERTISING_SERVICES", verticalCode: "MARKETING_ADTECH", nameRu: "Таргетированная реклама", nameEn: "Targeted advertising" },
  { code: "PROGRAMMATIC_PLATFORMS", verticalCode: "MARKETING_ADTECH", nameRu: "Programmatic", nameEn: "Programmatic platforms" },
  { code: "DISPLAY_ADVERTISING", verticalCode: "MARKETING_ADTECH", nameRu: "Медийная реклама", nameEn: "Display advertising" },
  { code: "NATIVE_ADVERTISING", verticalCode: "MARKETING_ADTECH", nameRu: "Нативная реклама", nameEn: "Native advertising" },
  { code: "AFFILIATE_PLATFORMS", verticalCode: "MARKETING_ADTECH", nameRu: "Партнёрские платформы", nameEn: "Affiliate platforms" },
  { code: "INFLUENCER_MARKETING", verticalCode: "MARKETING_ADTECH", nameRu: "Инфлюенс-маркетинг", nameEn: "Influencer marketing" },
  { code: "SEO_SERVICES", verticalCode: "MARKETING_ADTECH", nameRu: "SEO", nameEn: "SEO services" },
  { code: "ASO_SERVICES", verticalCode: "MARKETING_ADTECH", nameRu: "ASO", nameEn: "ASO services" },
  { code: "EMAIL_MARKETING_SERVICES", verticalCode: "MARKETING_ADTECH", nameRu: "Email-маркетинг", nameEn: "Email marketing" },
  { code: "MARKETING_AUTOMATION", verticalCode: "MARKETING_ADTECH", nameRu: "Маркетинговая автоматизация", nameEn: "Marketing automation" },
  { code: "ADTECH", verticalCode: "MARKETING_ADTECH", nameRu: "AdTech", nameEn: "AdTech" },
  { code: "MARKETING_ANALYTICS", verticalCode: "MARKETING_ADTECH", nameRu: "Маркетинговая аналитика", nameEn: "Marketing analytics" },
  { code: "CALL_TRACKING", verticalCode: "MARKETING_ADTECH", nameRu: "Коллтрекинг", nameEn: "Call tracking" },
  { code: "ATTRIBUTION_SOFTWARE", verticalCode: "MARKETING_ADTECH", nameRu: "Атрибуция", nameEn: "Attribution software" },
  { code: "LEAD_GENERATION_SERVICES", verticalCode: "MARKETING_ADTECH", nameRu: "Лидогенерация", nameEn: "Lead generation" },
  { code: "CONTENT_MARKETING", verticalCode: "MARKETING_ADTECH", nameRu: "Контент-маркетинг", nameEn: "Content marketing" },
  { code: "PR_SERVICES", verticalCode: "MARKETING_ADTECH", nameRu: "PR", nameEn: "PR services" },
  { code: "REPUTATION_MANAGEMENT", verticalCode: "MARKETING_ADTECH", nameRu: "Управление репутацией", nameEn: "Reputation management" },
  { code: "BUSINESS_CONSULTING", verticalCode: "B2B_SERVICES", nameRu: "Бизнес-консалтинг", nameEn: "Business consulting" },
  { code: "IT_CONSULTING", verticalCode: "B2B_SERVICES", nameRu: "IT-консалтинг", nameEn: "IT consulting" },
  { code: "AUDIT_SERVICES", verticalCode: "B2B_SERVICES", nameRu: "Аудит", nameEn: "Audit" },
  { code: "ACCOUNTING_SERVICES", verticalCode: "B2B_SERVICES", nameRu: "Бухгалтерские услуги", nameEn: "Accounting services" },
  { code: "TAX_SERVICES", verticalCode: "B2B_SERVICES", nameRu: "Налоги", nameEn: "Tax services" },
  { code: "IT_OUTSOURCING", verticalCode: "B2B_SERVICES", nameRu: "IT-аутсорсинг", nameEn: "IT outsourcing" },
  { code: "DEVELOPMENT_SERVICES", verticalCode: "B2B_SERVICES", nameRu: "Разработка", nameEn: "Development services" },
  { code: "DESIGN_SERVICES", verticalCode: "B2B_SERVICES", nameRu: "Дизайн-услуги", nameEn: "Design services" },
  { code: "CALL_CENTER_OUTSOURCING", verticalCode: "B2B_SERVICES", nameRu: "Колл-центры", nameEn: "Call center outsourcing" },
  { code: "CUSTOMER_SUPPORT_OUTSOURCING", verticalCode: "B2B_SERVICES", nameRu: "Поддержка клиентов", nameEn: "Customer support outsourcing" },
  { code: "SALES_OUTSOURCING", verticalCode: "B2B_SERVICES", nameRu: "Аутсорсинг продаж", nameEn: "Sales outsourcing" },
  { code: "RESEARCH_SERVICES", verticalCode: "B2B_SERVICES", nameRu: "Исследования", nameEn: "Research services" },
  { code: "TRANSLATION_SERVICES", verticalCode: "B2B_SERVICES", nameRu: "Переводы", nameEn: "Translation services" },
  { code: "MOBILE_OPERATORS", verticalCode: "TELECOM", nameRu: "Мобильные операторы", nameEn: "Mobile operators" },
  { code: "SIM_CARDS", verticalCode: "TELECOM", nameRu: "SIM-карты", nameEn: "SIM cards" },
  { code: "ESIM", verticalCode: "TELECOM", nameRu: "eSIM", nameEn: "eSIM" },
  { code: "HOME_INTERNET", verticalCode: "TELECOM", nameRu: "Домашний интернет", nameEn: "Home internet" },
  { code: "MOBILE_INTERNET", verticalCode: "TELECOM", nameRu: "Мобильный интернет", nameEn: "Mobile internet" },
  { code: "VOIP", verticalCode: "TELECOM", nameRu: "VoIP", nameEn: "VoIP" },
  { code: "VIRTUAL_PBX", verticalCode: "TELECOM", nameRu: "Виртуальная АТС", nameEn: "Virtual PBX" },
  { code: "BUSINESS_TELECOM", verticalCode: "TELECOM", nameRu: "Бизнес-телеком", nameEn: "Business telecom" },
  { code: "ROAMING", verticalCode: "TELECOM", nameRu: "Роуминг", nameEn: "Roaming" },
  { code: "INTERNATIONAL_CALLS", verticalCode: "TELECOM", nameRu: "Международные звонки", nameEn: "International calls" },
  { code: "PC_GAMES", verticalCode: "GAMING", nameRu: "PC-игры", nameEn: "PC games" },
  { code: "CONSOLE_GAMES", verticalCode: "GAMING", nameRu: "Консольные игры", nameEn: "Console games" },
  { code: "MOBILE_GAMES", verticalCode: "GAMING", nameRu: "Мобильные игры", nameEn: "Mobile games" },
  { code: "BROWSER_GAMES", verticalCode: "GAMING", nameRu: "Браузерные игры", nameEn: "Browser games" },
  { code: "CLOUD_GAMING", verticalCode: "GAMING", nameRu: "Облачный гейминг", nameEn: "Cloud gaming" },
  { code: "GAME_SUBSCRIPTIONS", verticalCode: "GAMING", nameRu: "Игровые подписки", nameEn: "Game subscriptions" },
  { code: "GAME_STORES", verticalCode: "GAMING", nameRu: "Игровые магазины", nameEn: "Game stores" },
  { code: "IN_GAME_ITEMS", verticalCode: "GAMING", nameRu: "Внутриигровые предметы", nameEn: "In-game items" },
  { code: "GAME_CURRENCY", verticalCode: "GAMING", nameRu: "Игровая валюта", nameEn: "Game currency" },
  { code: "ESPORTS_PLATFORMS", verticalCode: "GAMING", nameRu: "Киберспорт", nameEn: "Esports platforms" },
  { code: "GAME_STREAMING", verticalCode: "GAMING", nameRu: "Игровой стриминг", nameEn: "Game streaming" },
  { code: "ONLINE_CASINO", verticalCode: "IGAMING", nameRu: "Онлайн-казино", nameEn: "Online casino" },
  { code: "SLOTS", verticalCode: "IGAMING", nameRu: "Слоты", nameEn: "Slots" },
  { code: "LIVE_CASINO", verticalCode: "IGAMING", nameRu: "Live-казино", nameEn: "Live casino" },
  { code: "SPORTSBOOK", verticalCode: "IGAMING", nameRu: "Ставки на спорт", nameEn: "Sportsbook" },
  { code: "ESPORTS_BETTING", verticalCode: "IGAMING", nameRu: "Ставки на киберспорт", nameEn: "Esports betting" },
  { code: "POKER", verticalCode: "IGAMING", nameRu: "Покер", nameEn: "Poker" },
  { code: "BINGO", verticalCode: "IGAMING", nameRu: "Бинго", nameEn: "Bingo" },
  { code: "LOTTERY", verticalCode: "IGAMING", nameRu: "Лотереи", nameEn: "Lottery" },
  { code: "FANTASY_SPORTS", verticalCode: "IGAMING", nameRu: "Фэнтези-спорт", nameEn: "Fantasy sports" },
  { code: "SOCIAL_CASINO", verticalCode: "IGAMING", nameRu: "Social casino", nameEn: "Social casino" },
  { code: "PREDICTION_PLATFORMS", verticalCode: "IGAMING", nameRu: "Платформы прогнозов", nameEn: "Prediction platforms" },
  { code: "GENERAL_DATING", verticalCode: "DATING", nameRu: "Знакомства", nameEn: "General dating" },
  { code: "SERIOUS_DATING", verticalCode: "DATING", nameRu: "Серьёзные отношения", nameEn: "Serious dating" },
  { code: "CASUAL_DATING", verticalCode: "DATING", nameRu: "Casual-знакомства", nameEn: "Casual dating" },
  { code: "INTERNATIONAL_DATING", verticalCode: "DATING", nameRu: "Международные знакомства", nameEn: "International dating" },
  { code: "SENIOR_DATING", verticalCode: "DATING", nameRu: "Знакомства для старшего возраста", nameEn: "Senior dating" },
  { code: "NICHE_DATING", verticalCode: "DATING", nameRu: "Нишевые знакомства", nameEn: "Niche dating" },
  { code: "MATCHMAKING", verticalCode: "DATING", nameRu: "Сватовство", nameEn: "Matchmaking" },
  { code: "ADULT_CONTENT", verticalCode: "ADULT", nameRu: "Adult-контент", nameEn: "Adult content" },
  { code: "ADULT_DATING", verticalCode: "ADULT", nameRu: "Adult-знакомства", nameEn: "Adult dating" },
  { code: "ADULT_STREAMING", verticalCode: "ADULT", nameRu: "Adult-стриминг", nameEn: "Adult streaming" },
  { code: "ADULT_COMMUNITIES", verticalCode: "ADULT", nameRu: "Adult-сообщества", nameEn: "Adult communities" },
  { code: "CREATOR_ADULT_PLATFORMS", verticalCode: "ADULT", nameRu: "Adult-платформы для авторов", nameEn: "Creator adult platforms" },
  { code: "HOTELS", verticalCode: "TRAVEL", nameRu: "Отели", nameEn: "Hotels" },
  { code: "APARTMENTS", verticalCode: "TRAVEL", nameRu: "Апартаменты", nameEn: "Apartments" },
  { code: "HOSTELS", verticalCode: "TRAVEL", nameRu: "Хостелы", nameEn: "Hostels" },
  { code: "VACATION_RENTALS", verticalCode: "TRAVEL", nameRu: "Посуточная аренда", nameEn: "Vacation rentals" },
  { code: "FLIGHTS", verticalCode: "TRAVEL", nameRu: "Авиабилеты", nameEn: "Flights" },
  { code: "RAIL_TICKETS", verticalCode: "TRAVEL", nameRu: "Ж/д билеты", nameEn: "Rail tickets" },
  { code: "BUS_TICKETS", verticalCode: "TRAVEL", nameRu: "Автобусные билеты", nameEn: "Bus tickets" },
  { code: "CRUISES", verticalCode: "TRAVEL", nameRu: "Круизы", nameEn: "Cruises" },
  { code: "PACKAGE_TOURS", verticalCode: "TRAVEL", nameRu: "Пакетные туры", nameEn: "Package tours" },
  { code: "TOURS", verticalCode: "TRAVEL", nameRu: "Туры", nameEn: "Tours" },
  { code: "EXCURSIONS", verticalCode: "TRAVEL", nameRu: "Экскурсии", nameEn: "Excursions" },
  { code: "TRAVEL_ACTIVITIES", verticalCode: "TRAVEL", nameRu: "Активности в поездках", nameEn: "Travel activities" },
  { code: "CAR_RENTAL", verticalCode: "TRAVEL", nameRu: "Аренда авто", nameEn: "Car rental" },
  { code: "TRANSFERS", verticalCode: "TRAVEL", nameRu: "Трансферы", nameEn: "Transfers" },
  { code: "BUSINESS_TRAVEL", verticalCode: "TRAVEL", nameRu: "Деловые поездки", nameEn: "Business travel" },
  { code: "NEW_CARS", verticalCode: "AUTOMOTIVE", nameRu: "Новые автомобили", nameEn: "New cars" },
  { code: "USED_CARS", verticalCode: "AUTOMOTIVE", nameRu: "Автомобили с пробегом", nameEn: "Used cars" },
  { code: "AUTO_CLASSIFIEDS", verticalCode: "AUTOMOTIVE", nameRu: "Автообъявления", nameEn: "Auto classifieds" },
  { code: "AUTO_PARTS", verticalCode: "AUTOMOTIVE", nameRu: "Автозапчасти", nameEn: "Auto parts" },
  { code: "TIRES", verticalCode: "AUTOMOTIVE", nameRu: "Шины", nameEn: "Tires" },
  { code: "WHEELS", verticalCode: "AUTOMOTIVE", nameRu: "Диски", nameEn: "Wheels" },
  { code: "AUTO_ACCESSORIES", verticalCode: "AUTOMOTIVE", nameRu: "Автоаксессуары", nameEn: "Auto accessories" },
  { code: "AUTO_SERVICE", verticalCode: "AUTOMOTIVE", nameRu: "Автосервис", nameEn: "Auto service" },
  { code: "AUTO_REPAIR", verticalCode: "AUTOMOTIVE", nameRu: "Авторемонт", nameEn: "Auto repair" },
  { code: "AUTO_MAINTENANCE", verticalCode: "AUTOMOTIVE", nameRu: "Техобслуживание", nameEn: "Auto maintenance" },
  { code: "CAR_WASH", verticalCode: "AUTOMOTIVE", nameRu: "Автомойки", nameEn: "Car wash" },
  { code: "DETAILING", verticalCode: "AUTOMOTIVE", nameRu: "Детейлинг", nameEn: "Detailing" },
  { code: "ROADSIDE_ASSISTANCE", verticalCode: "AUTOMOTIVE", nameRu: "Помощь на дороге", nameEn: "Roadside assistance" },
  { code: "FUEL_SERVICES", verticalCode: "AUTOMOTIVE", nameRu: "Топливо", nameEn: "Fuel services" },
  { code: "CAR_SHARING", verticalCode: "AUTOMOTIVE", nameRu: "Каршеринг", nameEn: "Car sharing" },
  { code: "NEW_DEVELOPMENTS", verticalCode: "REAL_ESTATE", nameRu: "Новостройки", nameEn: "New developments" },
  { code: "RESALE_PROPERTY", verticalCode: "REAL_ESTATE", nameRu: "Вторичная недвижимость", nameEn: "Resale property" },
  { code: "APARTMENT_RENTAL", verticalCode: "REAL_ESTATE", nameRu: "Аренда квартир", nameEn: "Apartment rental" },
  { code: "HOUSE_RENTAL", verticalCode: "REAL_ESTATE", nameRu: "Аренда домов", nameEn: "House rental" },
  { code: "COMMERCIAL_REAL_ESTATE", verticalCode: "REAL_ESTATE", nameRu: "Коммерческая недвижимость", nameEn: "Commercial real estate" },
  { code: "COUNTRY_PROPERTY", verticalCode: "REAL_ESTATE", nameRu: "Загородная недвижимость", nameEn: "Country property" },
  { code: "LAND", verticalCode: "REAL_ESTATE", nameRu: "Земельные участки", nameEn: "Land" },
  { code: "OVERSEAS_PROPERTY", verticalCode: "REAL_ESTATE", nameRu: "Зарубежная недвижимость", nameEn: "Overseas property" },
  { code: "PROPERTY_MANAGEMENT", verticalCode: "REAL_ESTATE", nameRu: "Управление недвижимостью", nameEn: "Property management" },
  { code: "REAL_ESTATE_AGENCIES", verticalCode: "REAL_ESTATE", nameRu: "Агентства недвижимости", nameEn: "Real estate agencies" },
  { code: "PROPERTY_DEVELOPERS", verticalCode: "REAL_ESTATE", nameRu: "Девелоперы", nameEn: "Property developers" },
  { code: "CO_LIVING", verticalCode: "REAL_ESTATE", nameRu: "Коливинг", nameEn: "Co-living" },
  { code: "SELF_STORAGE", verticalCode: "REAL_ESTATE", nameRu: "Self storage", nameEn: "Self storage" },
  { code: "FURNITURE", verticalCode: "HOME_FURNITURE", nameRu: "Мебель", nameEn: "Furniture" },
  { code: "MATTRESSES", verticalCode: "HOME_FURNITURE", nameRu: "Матрасы", nameEn: "Mattresses" },
  { code: "LIGHTING", verticalCode: "HOME_FURNITURE", nameRu: "Освещение", nameEn: "Lighting" },
  { code: "HOME_DECOR", verticalCode: "HOME_FURNITURE", nameRu: "Декор", nameEn: "Home decor" },
  { code: "HOME_TEXTILES", verticalCode: "HOME_FURNITURE", nameRu: "Текстиль", nameEn: "Home textiles" },
  { code: "TABLEWARE", verticalCode: "HOME_FURNITURE", nameRu: "Посуда", nameEn: "Tableware" },
  { code: "KITCHEN_FURNITURE", verticalCode: "HOME_FURNITURE", nameRu: "Кухонная мебель", nameEn: "Kitchen furniture" },
  { code: "BATHROOM_FURNITURE", verticalCode: "HOME_FURNITURE", nameRu: "Мебель для ванной", nameEn: "Bathroom furniture" },
  { code: "HOME_STORAGE", verticalCode: "HOME_FURNITURE", nameRu: "Хранение", nameEn: "Home storage" },
  { code: "HOUSEHOLD_GOODS", verticalCode: "HOME_FURNITURE", nameRu: "Товары для дома", nameEn: "Household goods" },
  { code: "SMART_HOME_DEVICES", verticalCode: "HOME_FURNITURE", nameRu: "Умный дом", nameEn: "Smart home devices" },
  { code: "GARDEN_FURNITURE", verticalCode: "HOME_FURNITURE", nameRu: "Садовая мебель", nameEn: "Garden furniture" },
  { code: "BUILDING_MATERIALS", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Стройматериалы", nameEn: "Building materials" },
  { code: "TOOLS", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Инструменты", nameEn: "Tools" },
  { code: "APARTMENT_RENOVATION", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Ремонт квартир", nameEn: "Apartment renovation" },
  { code: "HOUSE_CONSTRUCTION", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Строительство домов", nameEn: "House construction" },
  { code: "INTERIOR_DESIGN", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Дизайн интерьера", nameEn: "Interior design" },
  { code: "ARCHITECTURE_SERVICES", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Архитектура", nameEn: "Architecture services" },
  { code: "PLUMBING_PRODUCTS", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Сантехника", nameEn: "Plumbing products" },
  { code: "ELECTRICAL_PRODUCTS", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Электрика", nameEn: "Electrical products" },
  { code: "WINDOWS", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Окна", nameEn: "Windows" },
  { code: "DOORS", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Двери", nameEn: "Doors" },
  { code: "FLOORING", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Напольные покрытия", nameEn: "Flooring" },
  { code: "PAINT_COATINGS", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Краски и покрытия", nameEn: "Paint & coatings" },
  { code: "ROOFING", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Кровля", nameEn: "Roofing" },
  { code: "HVAC", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "HVAC", nameEn: "HVAC" },
  { code: "HEATING", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Отопление", nameEn: "Heating" },
  { code: "VENTILATION", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Вентиляция", nameEn: "Ventilation" },
  { code: "SMART_HOME_INSTALLATION", verticalCode: "CONSTRUCTION_REPAIR", nameRu: "Установка умного дома", nameEn: "Smart home installation" },
  { code: "CLEANING_SERVICES", verticalCode: "HOME_SERVICES", nameRu: "Клининг", nameEn: "Cleaning services" },
  { code: "APPLIANCE_REPAIR", verticalCode: "HOME_SERVICES", nameRu: "Ремонт техники", nameEn: "Appliance repair" },
  { code: "PLUMBING_SERVICES", verticalCode: "HOME_SERVICES", nameRu: "Сантехнические услуги", nameEn: "Plumbing services" },
  { code: "ELECTRICIAN_SERVICES", verticalCode: "HOME_SERVICES", nameRu: "Услуги электрика", nameEn: "Electrician services" },
  { code: "HANDYMAN", verticalCode: "HOME_SERVICES", nameRu: "Мастер на час", nameEn: "Handyman" },
  { code: "PEST_CONTROL", verticalCode: "HOME_SERVICES", nameRu: "Дезинсекция", nameEn: "Pest control" },
  { code: "HOME_MOVING", verticalCode: "HOME_SERVICES", nameRu: "Переезды", nameEn: "Home moving" },
  { code: "GARDENING_SERVICES", verticalCode: "HOME_SERVICES", nameRu: "Садовники", nameEn: "Gardening services" },
  { code: "LANDSCAPING", verticalCode: "HOME_SERVICES", nameRu: "Ландшафт", nameEn: "Landscaping" },
  { code: "LOCKSMITH", verticalCode: "HOME_SERVICES", nameRu: "Вскрытие замков", nameEn: "Locksmith" },
  { code: "APPLIANCE_INSTALLATION", verticalCode: "HOME_SERVICES", nameRu: "Установка техники", nameEn: "Appliance installation" },
  { code: "ELECTRICITY_PROVIDERS", verticalCode: "ENERGY", nameRu: "Электроснабжение", nameEn: "Electricity providers" },
  { code: "GAS_PROVIDERS", verticalCode: "ENERGY", nameRu: "Газоснабжение", nameEn: "Gas providers" },
  { code: "SOLAR_PANELS", verticalCode: "ENERGY", nameRu: "Солнечные панели", nameEn: "Solar panels" },
  { code: "ENERGY_STORAGE", verticalCode: "ENERGY", nameRu: "Накопители энергии", nameEn: "Energy storage" },
  { code: "EV_CHARGING", verticalCode: "ENERGY", nameRu: "Зарядка электромобилей", nameEn: "EV charging" },
  { code: "ENERGY_EFFICIENCY", verticalCode: "ENERGY", nameRu: "Энергоэффективность", nameEn: "Energy efficiency" },
  { code: "SMART_METERS", verticalCode: "ENERGY", nameRu: "Умные счётчики", nameEn: "Smart meters" },
  { code: "GREEN_ENERGY", verticalCode: "ENERGY", nameRu: "Зелёная энергия", nameEn: "Green energy" },
  { code: "GROCERIES", verticalCode: "FOOD_GROCERY", nameRu: "Продукты", nameEn: "Groceries" },
  { code: "FRESH_FOOD", verticalCode: "FOOD_GROCERY", nameRu: "Свежие продукты", nameEn: "Fresh food" },
  { code: "ORGANIC_FOOD", verticalCode: "FOOD_GROCERY", nameRu: "Органические продукты", nameEn: "Organic food" },
  { code: "MEAL_KITS", verticalCode: "FOOD_GROCERY", nameRu: "Наборы еды", nameEn: "Meal kits" },
  { code: "SPECIALTY_FOOD", verticalCode: "FOOD_GROCERY", nameRu: "Специальные продукты", nameEn: "Specialty food" },
  { code: "COFFEE", verticalCode: "FOOD_GROCERY", nameRu: "Кофе", nameEn: "Coffee" },
  { code: "TEA", verticalCode: "FOOD_GROCERY", nameRu: "Чай", nameEn: "Tea" },
  { code: "SNACKS", verticalCode: "FOOD_GROCERY", nameRu: "Снеки", nameEn: "Snacks" },
  { code: "BAKERY", verticalCode: "FOOD_GROCERY", nameRu: "Выпечка", nameEn: "Bakery" },
  { code: "FOOD_SUBSCRIPTIONS", verticalCode: "FOOD_GROCERY", nameRu: "Продуктовые подписки", nameEn: "Food subscriptions" },
  { code: "RESTAURANTS", verticalCode: "RESTAURANTS_DELIVERY", nameRu: "Рестораны", nameEn: "Restaurants" },
  { code: "CAFES", verticalCode: "RESTAURANTS_DELIVERY", nameRu: "Кафе", nameEn: "Cafes" },
  { code: "FAST_FOOD", verticalCode: "RESTAURANTS_DELIVERY", nameRu: "Фастфуд", nameEn: "Fast food" },
  { code: "FOOD_DELIVERY", verticalCode: "RESTAURANTS_DELIVERY", nameRu: "Доставка еды", nameEn: "Food delivery" },
  { code: "RESTAURANT_BOOKING", verticalCode: "RESTAURANTS_DELIVERY", nameRu: "Бронирование столиков", nameEn: "Restaurant booking" },
  { code: "DARK_KITCHENS", verticalCode: "RESTAURANTS_DELIVERY", nameRu: "Dark kitchen", nameEn: "Dark kitchens" },
  { code: "CATERING", verticalCode: "RESTAURANTS_DELIVERY", nameRu: "Кейтеринг", nameEn: "Catering" },
  { code: "CORPORATE_CATERING", verticalCode: "RESTAURANTS_DELIVERY", nameRu: "Корпоративный кейтеринг", nameEn: "Corporate catering" },
  { code: "COURIER_SERVICES", verticalCode: "LOGISTICS", nameRu: "Курьерские услуги", nameEn: "Courier services" },
  { code: "LAST_MILE_DELIVERY", verticalCode: "LOGISTICS", nameRu: "Последняя миля", nameEn: "Last-mile delivery" },
  { code: "PARCEL_DELIVERY", verticalCode: "LOGISTICS", nameRu: "Доставка посылок", nameEn: "Parcel delivery" },
  { code: "INTERNATIONAL_DELIVERY", verticalCode: "LOGISTICS", nameRu: "Международная доставка", nameEn: "International delivery" },
  { code: "FREIGHT", verticalCode: "LOGISTICS", nameRu: "Грузоперевозки", nameEn: "Freight" },
  { code: "CARGO_TRANSPORTATION", verticalCode: "LOGISTICS", nameRu: "Транспортировка грузов", nameEn: "Cargo transportation" },
  { code: "FULFILLMENT", verticalCode: "LOGISTICS", nameRu: "Фулфилмент", nameEn: "Fulfillment" },
  { code: "WAREHOUSING", verticalCode: "LOGISTICS", nameRu: "Склады", nameEn: "Warehousing" },
  { code: "SHIPPING_PLATFORMS", verticalCode: "LOGISTICS", nameRu: "Платформы доставки", nameEn: "Shipping platforms" },
  { code: "POSTAL_SERVICES", verticalCode: "LOGISTICS", nameRu: "Почтовые услуги", nameEn: "Postal services" },
  { code: "LEGAL_CONSULTING", verticalCode: "LEGAL", nameRu: "Юридический консалтинг", nameEn: "Legal consulting" },
  { code: "FAMILY_LAW", verticalCode: "LEGAL", nameRu: "Семейное право", nameEn: "Family law" },
  { code: "CORPORATE_LAW", verticalCode: "LEGAL", nameRu: "Корпоративное право", nameEn: "Corporate law" },
  { code: "TAX_LAW", verticalCode: "LEGAL", nameRu: "Налоговое право", nameEn: "Tax law" },
  { code: "INTELLECTUAL_PROPERTY", verticalCode: "LEGAL", nameRu: "Интеллектуальная собственность", nameEn: "Intellectual property" },
  { code: "BANKRUPTCY", verticalCode: "LEGAL", nameRu: "Банкротство", nameEn: "Bankruptcy" },
  { code: "DEBT_COLLECTION", verticalCode: "LEGAL", nameRu: "Взыскание долгов", nameEn: "Debt collection" },
  { code: "LEGALTECH", verticalCode: "LEGAL", nameRu: "LegalTech", nameEn: "LegalTech" },
  { code: "LEGAL_DOCUMENTS", verticalCode: "LEGAL", nameRu: "Юридические документы", nameEn: "Legal documents" },
  { code: "COMPANY_REGISTRATION", verticalCode: "LEGAL", nameRu: "Регистрация компаний", nameEn: "Company registration" },
  { code: "TRADEMARK_REGISTRATION", verticalCode: "LEGAL", nameRu: "Регистрация товарных знаков", nameEn: "Trademark registration" },
  { code: "VISA_SERVICES", verticalCode: "IMMIGRATION_DOCUMENTS", nameRu: "Визы", nameEn: "Visa services" },
  { code: "IMMIGRATION_SERVICES", verticalCode: "IMMIGRATION_DOCUMENTS", nameRu: "Иммиграция", nameEn: "Immigration services" },
  { code: "RESIDENCE_PERMITS", verticalCode: "IMMIGRATION_DOCUMENTS", nameRu: "ВНЖ", nameEn: "Residence permits" },
  { code: "CITIZENSHIP_SERVICES", verticalCode: "IMMIGRATION_DOCUMENTS", nameRu: "Гражданство", nameEn: "Citizenship services" },
  { code: "MIGRATION_DOCUMENTS", verticalCode: "IMMIGRATION_DOCUMENTS", nameRu: "Миграционные документы", nameEn: "Migration documents" },
  { code: "NOTARY_SUPPORT", verticalCode: "IMMIGRATION_DOCUMENTS", nameRu: "Нотариальная поддержка", nameEn: "Notary support" },
  { code: "GOVERNMENT_APPLICATION_ASSISTANCE", verticalCode: "IMMIGRATION_DOCUMENTS", nameRu: "Помощь с госуслугами", nameEn: "Government application assistance" },
  { code: "VIDEO_STREAMING", verticalCode: "MEDIA_ENTERTAINMENT", nameRu: "Видеостриминг", nameEn: "Video streaming" },
  { code: "MUSIC_STREAMING", verticalCode: "MEDIA_ENTERTAINMENT", nameRu: "Музыкальный стриминг", nameEn: "Music streaming" },
  { code: "SPORTS_STREAMING", verticalCode: "MEDIA_ENTERTAINMENT", nameRu: "Спортивный стриминг", nameEn: "Sports streaming" },
  { code: "NEWS_SUBSCRIPTIONS", verticalCode: "MEDIA_ENTERTAINMENT", nameRu: "Новостные подписки", nameEn: "News subscriptions" },
  { code: "DIGITAL_MAGAZINES", verticalCode: "MEDIA_ENTERTAINMENT", nameRu: "Цифровые журналы", nameEn: "Digital magazines" },
  { code: "PODCASTS", verticalCode: "MEDIA_ENTERTAINMENT", nameRu: "Подкасты", nameEn: "Podcasts" },
  { code: "EBOOKS", verticalCode: "MEDIA_ENTERTAINMENT", nameRu: "Электронные книги", nameEn: "E-books" },
  { code: "AUDIOBOOKS", verticalCode: "MEDIA_ENTERTAINMENT", nameRu: "Аудиокниги", nameEn: "Audiobooks" },
  { code: "CREATOR_SUBSCRIPTIONS", verticalCode: "MEDIA_ENTERTAINMENT", nameRu: "Подписки на авторов", nameEn: "Creator subscriptions" },
  { code: "ONLINE_CINEMA", verticalCode: "MEDIA_ENTERTAINMENT", nameRu: "Онлайн-кинотеатры", nameEn: "Online cinema" },
  { code: "CONCERTS", verticalCode: "EVENTS_TICKETS", nameRu: "Концерты", nameEn: "Concerts" },
  { code: "THEATRE", verticalCode: "EVENTS_TICKETS", nameRu: "Театр", nameEn: "Theatre" },
  { code: "CINEMA_TICKETS", verticalCode: "EVENTS_TICKETS", nameRu: "Кинобилеты", nameEn: "Cinema tickets" },
  { code: "SPORTS_EVENTS", verticalCode: "EVENTS_TICKETS", nameRu: "Спортивные события", nameEn: "Sports events" },
  { code: "FESTIVALS", verticalCode: "EVENTS_TICKETS", nameRu: "Фестивали", nameEn: "Festivals" },
  { code: "CONFERENCES", verticalCode: "EVENTS_TICKETS", nameRu: "Конференции", nameEn: "Conferences" },
  { code: "BUSINESS_EVENTS", verticalCode: "EVENTS_TICKETS", nameRu: "Деловые события", nameEn: "Business events" },
  { code: "EXHIBITIONS", verticalCode: "EVENTS_TICKETS", nameRu: "Выставки", nameEn: "Exhibitions" },
  { code: "MUSEUMS", verticalCode: "EVENTS_TICKETS", nameRu: "Музеи", nameEn: "Museums" },
  { code: "ATTRACTIONS", verticalCode: "EVENTS_TICKETS", nameRu: "Достопримечательности", nameEn: "Attractions" },
  { code: "TICKET_PLATFORMS", verticalCode: "EVENTS_TICKETS", nameRu: "Билетные платформы", nameEn: "Ticket platforms" },
  { code: "PET_FOOD", verticalCode: "PETS", nameRu: "Корм для животных", nameEn: "Pet food" },
  { code: "PET_ACCESSORIES", verticalCode: "PETS", nameRu: "Зоотовары", nameEn: "Pet accessories" },
  { code: "VETERINARY_SERVICES", verticalCode: "PETS", nameRu: "Ветеринария", nameEn: "Veterinary services" },
  { code: "PET_GROOMING", verticalCode: "PETS", nameRu: "Груминг", nameEn: "Pet grooming" },
  { code: "PET_SITTING", verticalCode: "PETS", nameRu: "Передержка", nameEn: "Pet sitting" },
  { code: "PET_HOTELS", verticalCode: "PETS", nameRu: "Зоогостиницы", nameEn: "Pet hotels" },
  { code: "PET_TRAINING", verticalCode: "PETS", nameRu: "Дрессировка", nameEn: "Pet training" },
  { code: "PET_MARKETPLACES", verticalCode: "PETS", nameRu: "Зоомаркетплейсы", nameEn: "Pet marketplaces" },
  { code: "PET_HEALTH_PRODUCTS", verticalCode: "PETS", nameRu: "Здоровье животных", nameEn: "Pet health products" },
  { code: "BABY_PRODUCTS", verticalCode: "KIDS_FAMILY", nameRu: "Товары для малышей", nameEn: "Baby products" },
  { code: "TOYS", verticalCode: "KIDS_FAMILY", nameRu: "Игрушки", nameEn: "Toys" },
  { code: "KIDS_CLOTHING", verticalCode: "KIDS_FAMILY", nameRu: "Детская одежда", nameEn: "Kids clothing" },
  { code: "BABY_FOOD", verticalCode: "KIDS_FAMILY", nameRu: "Детское питание", nameEn: "Baby food" },
  { code: "BABY_CARE", verticalCode: "KIDS_FAMILY", nameRu: "Уход за детьми", nameEn: "Baby care" },
  { code: "MATERNITY_PRODUCTS", verticalCode: "KIDS_FAMILY", nameRu: "Товары для мам", nameEn: "Maternity products" },
  { code: "BABYSITTING", verticalCode: "KIDS_FAMILY", nameRu: "Няни", nameEn: "Babysitting" },
  { code: "CHILDRENS_CAMPS", verticalCode: "KIDS_FAMILY", nameRu: "Детские лагеря", nameEn: "Children's camps" },
  { code: "FAMILY_SERVICES", verticalCode: "KIDS_FAMILY", nameRu: "Семейные услуги", nameEn: "Family services" },
  { code: "PARENTING_PLATFORMS", verticalCode: "KIDS_FAMILY", nameRu: "Платформы для родителей", nameEn: "Parenting platforms" },
  { code: "ALARM_SYSTEMS", verticalCode: "PHYSICAL_SECURITY", nameRu: "Сигнализации", nameEn: "Alarm systems" },
  { code: "VIDEO_SURVEILLANCE", verticalCode: "PHYSICAL_SECURITY", nameRu: "Видеонаблюдение", nameEn: "Video surveillance" },
  { code: "ACCESS_CONTROL", verticalCode: "PHYSICAL_SECURITY", nameRu: "Контроль доступа", nameEn: "Access control" },
  { code: "SECURITY_SERVICES", verticalCode: "PHYSICAL_SECURITY", nameRu: "Охранные услуги", nameEn: "Security services" },
  { code: "HOME_SECURITY", verticalCode: "PHYSICAL_SECURITY", nameRu: "Безопасность дома", nameEn: "Home security" },
  { code: "BUSINESS_SECURITY", verticalCode: "PHYSICAL_SECURITY", nameRu: "Безопасность бизнеса", nameEn: "Business security" },
  { code: "PERSONAL_SECURITY", verticalCode: "PHYSICAL_SECURITY", nameRu: "Личная безопасность", nameEn: "Personal security" },
  { code: "PRINTING", verticalCode: "PRINT_PROMO", nameRu: "Полиграфия", nameEn: "Printing" },
  { code: "BUSINESS_CARDS", verticalCode: "PRINT_PROMO", nameRu: "Визитки", nameEn: "Business cards" },
  { code: "PACKAGING", verticalCode: "PRINT_PROMO", nameRu: "Упаковка", nameEn: "Packaging" },
  { code: "MERCHANDISE", verticalCode: "PRINT_PROMO", nameRu: "Мерч", nameEn: "Merchandise" },
  { code: "PROMOTIONAL_PRODUCTS", verticalCode: "PRINT_PROMO", nameRu: "Промопродукция", nameEn: "Promotional products" },
  { code: "CORPORATE_GIFTS", verticalCode: "PRINT_PROMO", nameRu: "Корпоративные подарки", nameEn: "Corporate gifts" },
  { code: "CUSTOM_BRANDED_APPAREL", verticalCode: "PRINT_PROMO", nameRu: "Брендированная одежда", nameEn: "Custom branded apparel" },
  { code: "SIGNAGE", verticalCode: "PRINT_PROMO", nameRu: "Вывески", nameEn: "Signage" },
  { code: "INDUSTRIAL_EQUIPMENT", verticalCode: "INDUSTRIAL", nameRu: "Промышленное оборудование", nameEn: "Industrial equipment" },
  { code: "MACHINERY", verticalCode: "INDUSTRIAL", nameRu: "Станки и машины", nameEn: "Machinery" },
  { code: "INDUSTRIAL_AUTOMATION", verticalCode: "INDUSTRIAL", nameRu: "Промышленная автоматизация", nameEn: "Industrial automation" },
  { code: "ROBOTICS", verticalCode: "INDUSTRIAL", nameRu: "Робототехника", nameEn: "Robotics" },
  { code: "INDUSTRIAL_COMPONENTS", verticalCode: "INDUSTRIAL", nameRu: "Комплектующие", nameEn: "Industrial components" },
  { code: "ELECTRICAL_EQUIPMENT", verticalCode: "INDUSTRIAL", nameRu: "Электрооборудование", nameEn: "Electrical equipment" },
  { code: "CONSTRUCTION_MACHINERY", verticalCode: "INDUSTRIAL", nameRu: "Строительная техника", nameEn: "Construction machinery" },
  { code: "RAW_MATERIALS", verticalCode: "INDUSTRIAL", nameRu: "Сырьё", nameEn: "Raw materials" },
  { code: "MANUFACTURING_SYSTEMS", verticalCode: "INDUSTRIAL", nameRu: "Производственные системы", nameEn: "Manufacturing systems" },
  { code: "AGRICULTURAL_EQUIPMENT", verticalCode: "AGRICULTURE", nameRu: "Сельхозтехника", nameEn: "Agricultural equipment" },
  { code: "SEEDS", verticalCode: "AGRICULTURE", nameRu: "Семена", nameEn: "Seeds" },
  { code: "FERTILIZERS", verticalCode: "AGRICULTURE", nameRu: "Удобрения", nameEn: "Fertilizers" },
  { code: "FARM_SUPPLIES", verticalCode: "AGRICULTURE", nameRu: "Товары для фермы", nameEn: "Farm supplies" },
  { code: "AGROTECH", verticalCode: "AGRICULTURE", nameRu: "Агротех", nameEn: "Agrotech" },
  { code: "LIVESTOCK", verticalCode: "AGRICULTURE", nameRu: "Животноводство", nameEn: "Livestock" },
  { code: "AGRICULTURAL_MARKETPLACES", verticalCode: "AGRICULTURE", nameRu: "Агромаркетплейсы", nameEn: "Agricultural marketplaces" },
  { code: "FARM_MANAGEMENT", verticalCode: "AGRICULTURE", nameRu: "Управление фермой", nameEn: "Farm management" },
  { code: "SWEEPSTAKES", verticalCode: "SWEEPSTAKES_PROMOTIONS", nameRu: "Розыгрыши", nameEn: "Sweepstakes" },
  { code: "PRIZE_DRAWS", verticalCode: "SWEEPSTAKES_PROMOTIONS", nameRu: "Призовые розыгрыши", nameEn: "Prize draws" },
  { code: "CONTESTS", verticalCode: "SWEEPSTAKES_PROMOTIONS", nameRu: "Конкурсы", nameEn: "Contests" },
  { code: "LOYALTY_PROMOTIONS", verticalCode: "SWEEPSTAKES_PROMOTIONS", nameRu: "Программы лояльности", nameEn: "Loyalty promotions" },
  { code: "PROMOTIONAL_COMPETITIONS", verticalCode: "SWEEPSTAKES_PROMOTIONS", nameRu: "Промо-конкурсы", nameEn: "Promotional competitions" },
  { code: "CHARITY_PLATFORMS", verticalCode: "CHARITY", nameRu: "Благотворительные платформы", nameEn: "Charity platforms" },
  { code: "DONATIONS", verticalCode: "CHARITY", nameRu: "Пожертвования", nameEn: "Donations" },
  { code: "NONPROFIT_FUNDRAISING", verticalCode: "CHARITY", nameRu: "Сбор средств НКО", nameEn: "Nonprofit fundraising" },
  { code: "CHARITY_CROWDFUNDING", verticalCode: "CHARITY", nameRu: "Благотворительный краудфандинг", nameEn: "Charity crowdfunding" },
  { code: "OTHER", verticalCode: "OTHER", nameRu: "Другое", nameEn: "Other" },
];

export const LEGACY_CATEGORY_MAP: Record<string, string> = {
  "SaaS": "CRM",
  "Fintech": "PAYMENT_SERVICES",
  "Education": "ONLINE_COURSES",
  "E-commerce": "GENERAL_ONLINE_STORES",
  "Marketing": "CONTEXTUAL_ADVERTISING_SERVICES",
  "Other": "OTHER",
};

const verticalByCode = new Map(VERTICALS.map((item) => [item.code, item]));
const categoryByCode = new Map(CATEGORIES.map((item) => [item.code, item]));
const legacyCategoryLower = new Map(
  Object.entries(LEGACY_CATEGORY_MAP).map(([key, value]) => [key.toLowerCase(), value]),
);

export function findCategory(code?: string | null): Category | undefined {
  if (!code) return undefined;
  const text = code.trim();
  return categoryByCode.get(text) ?? categoryByCode.get(text.toUpperCase());
}

export function findVertical(code?: string | null): Vertical | undefined {
  if (!code) return undefined;
  const text = code.trim();
  return verticalByCode.get(text) ?? verticalByCode.get(text.toUpperCase());
}

export function resolveCategoryCode(value?: string | null): string | null {
  if (value == null) return null;
  const text = value.trim();
  if (!text) return null;
  if (categoryByCode.has(text)) return text;
  if (text in LEGACY_CATEGORY_MAP) return LEGACY_CATEGORY_MAP[text];
  const upper = text.toUpperCase();
  if (categoryByCode.has(upper)) return upper;
  return legacyCategoryLower.get(text.toLowerCase()) ?? null;
}

export function categoryLabel(code?: string | null): string {
  const category = findCategory(resolveCategoryCode(code) ?? code);
  if (!category) return code || "";
  const vertical = findVertical(category.verticalCode);
  const verticalName = vertical?.nameRu ?? category.verticalCode;
  return `${verticalName} → ${category.nameRu}`;
}

export function categoriesByVertical(): Record<string, Category[]> {
  return CATEGORIES.reduce<Record<string, Category[]>>((acc, category) => {
    const list = acc[category.verticalCode] ?? [];
    list.push(category);
    acc[category.verticalCode] = list;
    return acc;
  }, {});
}

export function searchCategories(query?: string | null): Category[] {
  const text = (query ?? "").trim().toLowerCase();
  if (!text) return CATEGORIES;
  return CATEGORIES.filter((category) => {
    const vertical = findVertical(category.verticalCode);
    return (
      category.code.toLowerCase().includes(text) ||
      category.nameRu.toLowerCase().includes(text) ||
      category.nameEn.toLowerCase().includes(text) ||
      category.verticalCode.toLowerCase().includes(text) ||
      (vertical?.nameRu.toLowerCase().includes(text) ?? false) ||
      (vertical?.nameEn.toLowerCase().includes(text) ?? false)
    );
  });
}
