export type Country = {
  code: string;
  nameRu: string;
  nameEn: string;
};

export const COUNTRIES: Country[] = [
  { code: "AD", nameRu: "Андорра", nameEn: "Andorra" },
  { code: "AE", nameRu: "Объединённые Арабские Эмираты", nameEn: "United Arab Emirates" },
  { code: "AF", nameRu: "Афганистан", nameEn: "Afghanistan" },
  { code: "AG", nameRu: "Антигуа и Барбуда", nameEn: "Antigua and Barbuda" },
  { code: "AI", nameRu: "Ангилья", nameEn: "Anguilla" },
  { code: "AL", nameRu: "Албания", nameEn: "Albania" },
  { code: "AM", nameRu: "Армения", nameEn: "Armenia" },
  { code: "AO", nameRu: "Ангола", nameEn: "Angola" },
  { code: "AQ", nameRu: "Антарктида", nameEn: "Antarctica" },
  { code: "AR", nameRu: "Аргентина", nameEn: "Argentina" },
  { code: "AS", nameRu: "Американское Самоа", nameEn: "American Samoa" },
  { code: "AT", nameRu: "Австрия", nameEn: "Austria" },
  { code: "AU", nameRu: "Австралия", nameEn: "Australia" },
  { code: "AW", nameRu: "Аруба", nameEn: "Aruba" },
  { code: "AX", nameRu: "Аландские острова", nameEn: "Åland Islands" },
  { code: "AZ", nameRu: "Азербайджан", nameEn: "Azerbaijan" },
  { code: "BA", nameRu: "Босния и Герцеговина", nameEn: "Bosnia and Herzegovina" },
  { code: "BB", nameRu: "Барбадос", nameEn: "Barbados" },
  { code: "BD", nameRu: "Бангладеш", nameEn: "Bangladesh" },
  { code: "BE", nameRu: "Бельгия", nameEn: "Belgium" },
  { code: "BF", nameRu: "Буркина-Фасо", nameEn: "Burkina Faso" },
  { code: "BG", nameRu: "Болгария", nameEn: "Bulgaria" },
  { code: "BH", nameRu: "Бахрейн", nameEn: "Bahrain" },
  { code: "BI", nameRu: "Бурунди", nameEn: "Burundi" },
  { code: "BJ", nameRu: "Бенин", nameEn: "Benin" },
  { code: "BL", nameRu: "Сен-Бартелеми", nameEn: "Saint Barthélemy" },
  { code: "BM", nameRu: "Бермуды", nameEn: "Bermuda" },
  { code: "BN", nameRu: "Бруней", nameEn: "Brunei Darussalam" },
  { code: "BO", nameRu: "Боливия", nameEn: "Bolivia" },
  { code: "BQ", nameRu: "Бонэйр, Синт-Эстатиус и Саба", nameEn: "Bonaire, Sint Eustatius and Saba" },
  { code: "BR", nameRu: "Бразилия", nameEn: "Brazil" },
  { code: "BS", nameRu: "Багамы", nameEn: "Bahamas" },
  { code: "BT", nameRu: "Бутан", nameEn: "Bhutan" },
  { code: "BV", nameRu: "Остров Буве", nameEn: "Bouvet Island" },
  { code: "BW", nameRu: "Ботсвана", nameEn: "Botswana" },
  { code: "BY", nameRu: "Беларусь", nameEn: "Belarus" },
  { code: "BZ", nameRu: "Белиз", nameEn: "Belize" },
  { code: "CA", nameRu: "Канада", nameEn: "Canada" },
  { code: "CC", nameRu: "Кокосовые острова", nameEn: "Cocos (Keeling) Islands" },
  { code: "CD", nameRu: "Демократическая Республика Конго", nameEn: "Congo, Democratic Republic of the" },
  { code: "CF", nameRu: "Центральноафриканская Республика", nameEn: "Central African Republic" },
  { code: "CG", nameRu: "Республика Конго", nameEn: "Congo" },
  { code: "CH", nameRu: "Швейцария", nameEn: "Switzerland" },
  { code: "CI", nameRu: "Кот-д’Ивуар", nameEn: "Côte d'Ivoire" },
  { code: "CK", nameRu: "Острова Кука", nameEn: "Cook Islands" },
  { code: "CL", nameRu: "Чили", nameEn: "Chile" },
  { code: "CM", nameRu: "Камерун", nameEn: "Cameroon" },
  { code: "CN", nameRu: "Китай", nameEn: "China" },
  { code: "CO", nameRu: "Колумбия", nameEn: "Colombia" },
  { code: "CR", nameRu: "Коста-Рика", nameEn: "Costa Rica" },
  { code: "CU", nameRu: "Куба", nameEn: "Cuba" },
  { code: "CV", nameRu: "Кабо-Верде", nameEn: "Cabo Verde" },
  { code: "CW", nameRu: "Кюрасао", nameEn: "Curaçao" },
  { code: "CX", nameRu: "Остров Рождества", nameEn: "Christmas Island" },
  { code: "CY", nameRu: "Кипр", nameEn: "Cyprus" },
  { code: "CZ", nameRu: "Чехия", nameEn: "Czechia" },
  { code: "DE", nameRu: "Германия", nameEn: "Germany" },
  { code: "DJ", nameRu: "Джибути", nameEn: "Djibouti" },
  { code: "DK", nameRu: "Дания", nameEn: "Denmark" },
  { code: "DM", nameRu: "Доминика", nameEn: "Dominica" },
  { code: "DO", nameRu: "Доминиканская Республика", nameEn: "Dominican Republic" },
  { code: "DZ", nameRu: "Алжир", nameEn: "Algeria" },
  { code: "EC", nameRu: "Эквадор", nameEn: "Ecuador" },
  { code: "EE", nameRu: "Эстония", nameEn: "Estonia" },
  { code: "EG", nameRu: "Египет", nameEn: "Egypt" },
  { code: "EH", nameRu: "Западная Сахара", nameEn: "Western Sahara" },
  { code: "ER", nameRu: "Эритрея", nameEn: "Eritrea" },
  { code: "ES", nameRu: "Испания", nameEn: "Spain" },
  { code: "ET", nameRu: "Эфиопия", nameEn: "Ethiopia" },
  { code: "FI", nameRu: "Финляндия", nameEn: "Finland" },
  { code: "FJ", nameRu: "Фиджи", nameEn: "Fiji" },
  { code: "FK", nameRu: "Фолклендские острова", nameEn: "Falkland Islands" },
  { code: "FM", nameRu: "Микронезия", nameEn: "Micronesia" },
  { code: "FO", nameRu: "Фарерские острова", nameEn: "Faroe Islands" },
  { code: "FR", nameRu: "Франция", nameEn: "France" },
  { code: "GA", nameRu: "Габон", nameEn: "Gabon" },
  { code: "GB", nameRu: "Великобритания", nameEn: "United Kingdom" },
  { code: "GD", nameRu: "Гренада", nameEn: "Grenada" },
  { code: "GE", nameRu: "Грузия", nameEn: "Georgia" },
  { code: "GF", nameRu: "Французская Гвиана", nameEn: "French Guiana" },
  { code: "GG", nameRu: "Гернси", nameEn: "Guernsey" },
  { code: "GH", nameRu: "Гана", nameEn: "Ghana" },
  { code: "GI", nameRu: "Гибралтар", nameEn: "Gibraltar" },
  { code: "GL", nameRu: "Гренландия", nameEn: "Greenland" },
  { code: "GM", nameRu: "Гамбия", nameEn: "Gambia" },
  { code: "GN", nameRu: "Гвинея", nameEn: "Guinea" },
  { code: "GP", nameRu: "Гваделупа", nameEn: "Guadeloupe" },
  { code: "GQ", nameRu: "Экваториальная Гвинея", nameEn: "Equatorial Guinea" },
  { code: "GR", nameRu: "Греция", nameEn: "Greece" },
  { code: "GS", nameRu: "Южная Георгия и Южные Сандвичевы острова", nameEn: "South Georgia and the South Sandwich Islands" },
  { code: "GT", nameRu: "Гватемала", nameEn: "Guatemala" },
  { code: "GU", nameRu: "Гуам", nameEn: "Guam" },
  { code: "GW", nameRu: "Гвинея-Бисау", nameEn: "Guinea-Bissau" },
  { code: "GY", nameRu: "Гайана", nameEn: "Guyana" },
  { code: "HK", nameRu: "Гонконг", nameEn: "Hong Kong" },
  { code: "HM", nameRu: "Остров Херд и острова Макдональд", nameEn: "Heard Island and McDonald Islands" },
  { code: "HN", nameRu: "Гондурас", nameEn: "Honduras" },
  { code: "HR", nameRu: "Хорватия", nameEn: "Croatia" },
  { code: "HT", nameRu: "Гаити", nameEn: "Haiti" },
  { code: "HU", nameRu: "Венгрия", nameEn: "Hungary" },
  { code: "ID", nameRu: "Индонезия", nameEn: "Indonesia" },
  { code: "IE", nameRu: "Ирландия", nameEn: "Ireland" },
  { code: "IL", nameRu: "Израиль", nameEn: "Israel" },
  { code: "IM", nameRu: "Остров Мэн", nameEn: "Isle of Man" },
  { code: "IN", nameRu: "Индия", nameEn: "India" },
  { code: "IO", nameRu: "Британская территория в Индийском океане", nameEn: "British Indian Ocean Territory" },
  { code: "IQ", nameRu: "Ирак", nameEn: "Iraq" },
  { code: "IR", nameRu: "Иран", nameEn: "Iran" },
  { code: "IS", nameRu: "Исландия", nameEn: "Iceland" },
  { code: "IT", nameRu: "Италия", nameEn: "Italy" },
  { code: "JE", nameRu: "Джерси", nameEn: "Jersey" },
  { code: "JM", nameRu: "Ямайка", nameEn: "Jamaica" },
  { code: "JO", nameRu: "Иордания", nameEn: "Jordan" },
  { code: "JP", nameRu: "Япония", nameEn: "Japan" },
  { code: "KE", nameRu: "Кения", nameEn: "Kenya" },
  { code: "KG", nameRu: "Кыргызстан", nameEn: "Kyrgyzstan" },
  { code: "KH", nameRu: "Камбоджа", nameEn: "Cambodia" },
  { code: "KI", nameRu: "Кирибати", nameEn: "Kiribati" },
  { code: "KM", nameRu: "Коморы", nameEn: "Comoros" },
  { code: "KN", nameRu: "Сент-Китс и Невис", nameEn: "Saint Kitts and Nevis" },
  { code: "KP", nameRu: "КНДР", nameEn: "Korea, Democratic People's Republic of" },
  { code: "KR", nameRu: "Республика Корея", nameEn: "Korea, Republic of" },
  { code: "KW", nameRu: "Кувейт", nameEn: "Kuwait" },
  { code: "KY", nameRu: "Острова Кайман", nameEn: "Cayman Islands" },
  { code: "KZ", nameRu: "Казахстан", nameEn: "Kazakhstan" },
  { code: "LA", nameRu: "Лаос", nameEn: "Lao People's Democratic Republic" },
  { code: "LB", nameRu: "Ливан", nameEn: "Lebanon" },
  { code: "LC", nameRu: "Сент-Люсия", nameEn: "Saint Lucia" },
  { code: "LI", nameRu: "Лихтенштейн", nameEn: "Liechtenstein" },
  { code: "LK", nameRu: "Шри-Ланка", nameEn: "Sri Lanka" },
  { code: "LR", nameRu: "Либерия", nameEn: "Liberia" },
  { code: "LS", nameRu: "Лесото", nameEn: "Lesotho" },
  { code: "LT", nameRu: "Литва", nameEn: "Lithuania" },
  { code: "LU", nameRu: "Люксембург", nameEn: "Luxembourg" },
  { code: "LV", nameRu: "Латвия", nameEn: "Latvia" },
  { code: "LY", nameRu: "Ливия", nameEn: "Libya" },
  { code: "MA", nameRu: "Марокко", nameEn: "Morocco" },
  { code: "MC", nameRu: "Монако", nameEn: "Monaco" },
  { code: "MD", nameRu: "Молдова", nameEn: "Moldova" },
  { code: "ME", nameRu: "Черногория", nameEn: "Montenegro" },
  { code: "MF", nameRu: "Сен-Мартен", nameEn: "Saint Martin (French part)" },
  { code: "MG", nameRu: "Мадагаскар", nameEn: "Madagascar" },
  { code: "MH", nameRu: "Маршалловы Острова", nameEn: "Marshall Islands" },
  { code: "MK", nameRu: "Северная Македония", nameEn: "North Macedonia" },
  { code: "ML", nameRu: "Мали", nameEn: "Mali" },
  { code: "MM", nameRu: "Мьянма", nameEn: "Myanmar" },
  { code: "MN", nameRu: "Монголия", nameEn: "Mongolia" },
  { code: "MO", nameRu: "Макао", nameEn: "Macao" },
  { code: "MP", nameRu: "Северные Марианские Острова", nameEn: "Northern Mariana Islands" },
  { code: "MQ", nameRu: "Мартиника", nameEn: "Martinique" },
  { code: "MR", nameRu: "Мавритания", nameEn: "Mauritania" },
  { code: "MS", nameRu: "Монтсеррат", nameEn: "Montserrat" },
  { code: "MT", nameRu: "Мальта", nameEn: "Malta" },
  { code: "MU", nameRu: "Маврикий", nameEn: "Mauritius" },
  { code: "MV", nameRu: "Мальдивы", nameEn: "Maldives" },
  { code: "MW", nameRu: "Малави", nameEn: "Malawi" },
  { code: "MX", nameRu: "Мексика", nameEn: "Mexico" },
  { code: "MY", nameRu: "Малайзия", nameEn: "Malaysia" },
  { code: "MZ", nameRu: "Мозамбик", nameEn: "Mozambique" },
  { code: "NA", nameRu: "Намибия", nameEn: "Namibia" },
  { code: "NC", nameRu: "Новая Каледония", nameEn: "New Caledonia" },
  { code: "NE", nameRu: "Нигер", nameEn: "Niger" },
  { code: "NF", nameRu: "Остров Норфолк", nameEn: "Norfolk Island" },
  { code: "NG", nameRu: "Нигерия", nameEn: "Nigeria" },
  { code: "NI", nameRu: "Никарагуа", nameEn: "Nicaragua" },
  { code: "NL", nameRu: "Нидерланды", nameEn: "Netherlands" },
  { code: "NO", nameRu: "Норвегия", nameEn: "Norway" },
  { code: "NP", nameRu: "Непал", nameEn: "Nepal" },
  { code: "NR", nameRu: "Науру", nameEn: "Nauru" },
  { code: "NU", nameRu: "Ниуэ", nameEn: "Niue" },
  { code: "NZ", nameRu: "Новая Зеландия", nameEn: "New Zealand" },
  { code: "OM", nameRu: "Оман", nameEn: "Oman" },
  { code: "PA", nameRu: "Панама", nameEn: "Panama" },
  { code: "PE", nameRu: "Перу", nameEn: "Peru" },
  { code: "PF", nameRu: "Французская Полинезия", nameEn: "French Polynesia" },
  { code: "PG", nameRu: "Папуа — Новая Гвинея", nameEn: "Papua New Guinea" },
  { code: "PH", nameRu: "Филиппины", nameEn: "Philippines" },
  { code: "PK", nameRu: "Пакистан", nameEn: "Pakistan" },
  { code: "PL", nameRu: "Польша", nameEn: "Poland" },
  { code: "PM", nameRu: "Сен-Пьер и Микелон", nameEn: "Saint Pierre and Miquelon" },
  { code: "PN", nameRu: "Острова Питкэрн", nameEn: "Pitcairn" },
  { code: "PR", nameRu: "Пуэрто-Рико", nameEn: "Puerto Rico" },
  { code: "PS", nameRu: "Палестина", nameEn: "Palestine, State of" },
  { code: "PT", nameRu: "Португалия", nameEn: "Portugal" },
  { code: "PW", nameRu: "Палау", nameEn: "Palau" },
  { code: "PY", nameRu: "Парагвай", nameEn: "Paraguay" },
  { code: "QA", nameRu: "Катар", nameEn: "Qatar" },
  { code: "RE", nameRu: "Реюньон", nameEn: "Réunion" },
  { code: "RO", nameRu: "Румыния", nameEn: "Romania" },
  { code: "RS", nameRu: "Сербия", nameEn: "Serbia" },
  { code: "RU", nameRu: "Россия", nameEn: "Russian Federation" },
  { code: "RW", nameRu: "Руанда", nameEn: "Rwanda" },
  { code: "SA", nameRu: "Саудовская Аравия", nameEn: "Saudi Arabia" },
  { code: "SB", nameRu: "Соломоновы Острова", nameEn: "Solomon Islands" },
  { code: "SC", nameRu: "Сейшельские Острова", nameEn: "Seychelles" },
  { code: "SD", nameRu: "Судан", nameEn: "Sudan" },
  { code: "SE", nameRu: "Швеция", nameEn: "Sweden" },
  { code: "SG", nameRu: "Сингапур", nameEn: "Singapore" },
  { code: "SH", nameRu: "Остров Святой Елены", nameEn: "Saint Helena, Ascension and Tristan da Cunha" },
  { code: "SI", nameRu: "Словения", nameEn: "Slovenia" },
  { code: "SJ", nameRu: "Шпицберген и Ян-Майен", nameEn: "Svalbard and Jan Mayen" },
  { code: "SK", nameRu: "Словакия", nameEn: "Slovakia" },
  { code: "SL", nameRu: "Сьерра-Леоне", nameEn: "Sierra Leone" },
  { code: "SM", nameRu: "Сан-Марино", nameEn: "San Marino" },
  { code: "SN", nameRu: "Сенегал", nameEn: "Senegal" },
  { code: "SO", nameRu: "Сомали", nameEn: "Somalia" },
  { code: "SR", nameRu: "Суринам", nameEn: "Suriname" },
  { code: "SS", nameRu: "Южный Судан", nameEn: "South Sudan" },
  { code: "ST", nameRu: "Сан-Томе и Принсипи", nameEn: "Sao Tome and Principe" },
  { code: "SV", nameRu: "Сальвадор", nameEn: "El Salvador" },
  { code: "SX", nameRu: "Синт-Мартен", nameEn: "Sint Maarten (Dutch part)" },
  { code: "SY", nameRu: "Сирия", nameEn: "Syrian Arab Republic" },
  { code: "SZ", nameRu: "Эсватини", nameEn: "Eswatini" },
  { code: "TC", nameRu: "Теркс и Кайкос", nameEn: "Turks and Caicos Islands" },
  { code: "TD", nameRu: "Чад", nameEn: "Chad" },
  { code: "TF", nameRu: "Французские Южные территории", nameEn: "French Southern Territories" },
  { code: "TG", nameRu: "Того", nameEn: "Togo" },
  { code: "TH", nameRu: "Таиланд", nameEn: "Thailand" },
  { code: "TJ", nameRu: "Таджикистан", nameEn: "Tajikistan" },
  { code: "TK", nameRu: "Токелау", nameEn: "Tokelau" },
  { code: "TL", nameRu: "Восточный Тимор", nameEn: "Timor-Leste" },
  { code: "TM", nameRu: "Туркменистан", nameEn: "Turkmenistan" },
  { code: "TN", nameRu: "Тунис", nameEn: "Tunisia" },
  { code: "TO", nameRu: "Тонга", nameEn: "Tonga" },
  { code: "TR", nameRu: "Турция", nameEn: "Türkiye" },
  { code: "TT", nameRu: "Тринидад и Тобаго", nameEn: "Trinidad and Tobago" },
  { code: "TV", nameRu: "Тувалу", nameEn: "Tuvalu" },
  { code: "TW", nameRu: "Тайвань", nameEn: "Taiwan" },
  { code: "TZ", nameRu: "Танзания", nameEn: "Tanzania" },
  { code: "UA", nameRu: "Украина", nameEn: "Ukraine" },
  { code: "UG", nameRu: "Уганда", nameEn: "Uganda" },
  { code: "UM", nameRu: "Внешние малые острова США", nameEn: "United States Minor Outlying Islands" },
  { code: "US", nameRu: "США", nameEn: "United States" },
  { code: "UY", nameRu: "Уругвай", nameEn: "Uruguay" },
  { code: "UZ", nameRu: "Узбекистан", nameEn: "Uzbekistan" },
  { code: "VA", nameRu: "Ватикан", nameEn: "Holy See" },
  { code: "VC", nameRu: "Сент-Винсент и Гренадины", nameEn: "Saint Vincent and the Grenadines" },
  { code: "VE", nameRu: "Венесуэла", nameEn: "Venezuela" },
  { code: "VG", nameRu: "Виргинские Острова (Великобритания)", nameEn: "Virgin Islands (British)" },
  { code: "VI", nameRu: "Виргинские Острова (США)", nameEn: "Virgin Islands (U.S.)" },
  { code: "VN", nameRu: "Вьетнам", nameEn: "Viet Nam" },
  { code: "VU", nameRu: "Вануату", nameEn: "Vanuatu" },
  { code: "WF", nameRu: "Уоллис и Футуна", nameEn: "Wallis and Futuna" },
  { code: "WS", nameRu: "Самоа", nameEn: "Samoa" },
  { code: "YE", nameRu: "Йемен", nameEn: "Yemen" },
  { code: "YT", nameRu: "Майотта", nameEn: "Mayotte" },
  { code: "ZA", nameRu: "Южно-Африканская Республика", nameEn: "South Africa" },
  { code: "ZM", nameRu: "Замбия", nameEn: "Zambia" },
  { code: "ZW", nameRu: "Зимбабве", nameEn: "Zimbabwe" },
];

const countryMap = new Map(COUNTRIES.map((item) => [item.code, item]));
const REGIONAL_INDICATOR_A = 0x1f1e6;

export function countryByCode(code?: string | null): Country | undefined {
  if (!code) return undefined;
  return countryMap.get(code.trim().toUpperCase());
}

export function countryFlag(code?: string | null): string {
  const country = countryByCode(code);
  if (!country) return "";
  return [...country.code]
    .map((char) => String.fromCodePoint(REGIONAL_INDICATOR_A + char.charCodeAt(0) - 65))
    .join("");
}

export function searchCountries(query?: string | null): Country[] {
  const text = (query ?? "").trim().toLowerCase();
  if (!text) return COUNTRIES;
  return COUNTRIES.filter(
    (item) =>
      item.code.toLowerCase().includes(text) ||
      item.nameRu.toLowerCase().includes(text) ||
      item.nameEn.toLowerCase().includes(text),
  );
}

export function parseGeoCodes(value?: string | Iterable<string> | null): string[] {
  if (value == null) return [];
  const raw = typeof value === "string"
    ? value.replace(/;/g, ",").split(",")
    : Array.from(value);
  const seen = new Set<string>();
  const result: string[] = [];
  for (const part of raw) {
    const code = String(part).trim().toUpperCase();
    if (!code || seen.has(code) || !countryMap.has(code)) continue;
    seen.add(code);
    result.push(code);
  }
  return result;
}
