from __future__ import annotations

VERTICALS: list[tuple[str, str, str]] = [
    ("FINANCE", "Финансы", "Finance"),
    ("INSURANCE", "Страхование", "Insurance"),
    ("CRYPTO_WEB3", "Криптовалюты / Web3", "Crypto / Web3"),
    ("RETAIL", "Универсальный ритейл", "Retail"),
    ("FASHION", "Одежда и аксессуары", "Fashion"),
    ("BEAUTY", "Красота", "Beauty"),
    ("ELECTRONICS", "Электроника", "Electronics"),
    ("HEALTH", "Здоровье и медицина", "Health"),
    ("NUTRA", "Nutra / БАД", "Nutra"),
    ("SPORTS_FITNESS", "Спорт и фитнес", "Sports & Fitness"),
    ("EDUCATION", "Образование", "Education"),
    ("HR_JOBS", "Работа и HR", "HR & Jobs"),
    ("SAAS", "SaaS / горизонтальное ПО", "SaaS"),
    ("CYBERSECURITY", "Кибербезопасность", "Cybersecurity"),
    ("HOSTING_INFRA", "Хостинг и инфраструктура", "Hosting & Infrastructure"),
    ("MARKETING_ADTECH", "Маркетинг и AdTech", "Marketing & AdTech"),
    ("B2B_SERVICES", "Бизнес-услуги", "B2B Services"),
    ("TELECOM", "Телеком", "Telecom"),
    ("GAMING", "Игры", "Gaming"),
    ("IGAMING", "iGaming", "iGaming"),
    ("DATING", "Знакомства", "Dating"),
    ("ADULT", "Adult", "Adult"),
    ("TRAVEL", "Путешествия", "Travel"),
    ("AUTOMOTIVE", "Автомобили", "Automotive"),
    ("REAL_ESTATE", "Недвижимость", "Real Estate"),
    ("HOME_FURNITURE", "Дом и мебель", "Home & Furniture"),
    ("CONSTRUCTION_REPAIR", "Строительство и ремонт", "Construction & Repair"),
    ("HOME_SERVICES", "Бытовые услуги", "Home Services"),
    ("ENERGY", "Энергетика", "Energy"),
    ("FOOD_GROCERY", "Продукты", "Food & Grocery"),
    ("RESTAURANTS_DELIVERY", "Рестораны и готовая еда", "Restaurants & Delivery"),
    ("LOGISTICS", "Логистика", "Logistics"),
    ("LEGAL", "Юридические услуги", "Legal"),
    ("IMMIGRATION_DOCUMENTS", "Миграция и документы", "Immigration & Documents"),
    ("MEDIA_ENTERTAINMENT", "Медиа и развлечения", "Media & Entertainment"),
    ("EVENTS_TICKETS", "События и билеты", "Events & Tickets"),
    ("PETS", "Животные", "Pets"),
    ("KIDS_FAMILY", "Дети и семья", "Kids & Family"),
    ("PHYSICAL_SECURITY", "Физическая безопасность", "Physical Security"),
    ("PRINT_PROMO", "Полиграфия и промопродукция", "Print & Promo"),
    ("INDUSTRIAL", "Промышленность", "Industrial"),
    ("AGRICULTURE", "Сельское хозяйство", "Agriculture"),
    ("SWEEPSTAKES_PROMOTIONS", "Розыгрыши и промо", "Sweepstakes & Promotions"),
    ("CHARITY", "Благотворительность", "Charity"),
    ("OTHER", "Другое", "Other"),
]

CATEGORIES: list[tuple[str, str, str, str]] = [
    ("FINANCE", "DEBIT_CARDS", "Дебетовые карты", "Debit cards"),
    ("FINANCE", "CREDIT_CARDS", "Кредитные карты", "Credit cards"),
    ("FINANCE", "INSTALLMENT_CARDS", "Карты рассрочки", "Installment cards"),
    ("FINANCE", "PERSONAL_BANK_ACCOUNTS", "Банковские счета физлиц", "Personal bank accounts"),
    ("FINANCE", "BUSINESS_BANK_ACCOUNTS", "Расчётные счета бизнеса", "Business bank accounts"),
    ("FINANCE", "CASH_MANAGEMENT", "РКО", "Cash management"),
    ("FINANCE", "ACQUIRING", "Эквайринг", "Acquiring"),
    ("FINANCE", "CONSUMER_LOANS", "Потребительские кредиты", "Consumer loans"),
    ("FINANCE", "CASH_LOANS", "Кредиты наличными", "Cash loans"),
    ("FINANCE", "AUTO_LOANS", "Автокредиты", "Auto loans"),
    ("FINANCE", "MORTGAGE", "Ипотека", "Mortgage"),
    ("FINANCE", "REFINANCING", "Рефинансирование", "Refinancing"),
    ("FINANCE", "MICROLOANS", "Микрозаймы", "Microloans"),
    ("FINANCE", "BNPL", "BNPL / оплата частями", "BNPL"),
    ("FINANCE", "INSTALLMENT_FINANCE", "Финансовая рассрочка", "Installment finance"),
    ("FINANCE", "DEPOSITS", "Вклады", "Deposits"),
    ("FINANCE", "SAVINGS_ACCOUNTS", "Накопительные счета", "Savings accounts"),
    ("FINANCE", "BROKERAGE", "Брокерские услуги", "Brokerage"),
    ("FINANCE", "INVESTMENT_ACCOUNTS", "Инвестиционные счета", "Investment accounts"),
    ("FINANCE", "ASSET_MANAGEMENT", "Управление активами", "Asset management"),
    ("FINANCE", "ROBO_ADVISORY", "Робоэдвайзинг", "Robo-advisory"),
    ("FINANCE", "FOREX", "Forex", "Forex"),
    ("FINANCE", "MONEY_TRANSFERS", "Денежные переводы", "Money transfers"),
    ("FINANCE", "PAYMENT_SERVICES", "Платёжные сервисы", "Payment services"),
    ("FINANCE", "E_WALLETS", "Электронные кошельки", "E-wallets"),
    ("FINANCE", "BUSINESS_LOANS", "Кредиты бизнесу", "Business loans"),
    ("FINANCE", "FACTORING", "Факторинг", "Factoring"),
    ("FINANCE", "LEASING", "Лизинг", "Leasing"),
    ("FINANCE", "CROWDLENDING", "Краудлендинг", "Crowdlending"),
    ("FINANCE", "INVESTMENT_CROWDFUNDING", "Инвестиционный краудфандинг", "Investment crowdfunding"),
    ("FINANCE", "CREDIT_HISTORY", "Кредитные истории", "Credit history"),
    ("FINANCE", "DEBT_RESTRUCTURING", "Реструктуризация задолженности", "Debt restructuring"),
    ("INSURANCE", "OSAGO", "ОСАГО", "OSAGO"),
    ("INSURANCE", "CASCO", "КАСКО", "CASCO"),
    ("INSURANCE", "LIFE_INSURANCE", "Страхование жизни", "Life insurance"),
    ("INSURANCE", "HEALTH_INSURANCE", "Медицинское страхование", "Health insurance"),
    ("INSURANCE", "DMS", "ДМС", "Voluntary health insurance"),
    ("INSURANCE", "TRAVEL_INSURANCE", "Страхование путешествий", "Travel insurance"),
    ("INSURANCE", "PROPERTY_INSURANCE", "Страхование имущества", "Property insurance"),
    ("INSURANCE", "HOME_INSURANCE", "Страхование жилья", "Home insurance"),
    ("INSURANCE", "ACCIDENT_INSURANCE", "Страхование от несчастных случаев", "Accident insurance"),
    ("INSURANCE", "LIABILITY_INSURANCE", "Страхование ответственности", "Liability insurance"),
    ("INSURANCE", "BUSINESS_INSURANCE", "Страхование бизнеса", "Business insurance"),
    ("INSURANCE", "PET_INSURANCE", "Страхование животных", "Pet insurance"),
    ("INSURANCE", "DEVICE_INSURANCE", "Страхование техники", "Device insurance"),
    ("INSURANCE", "CYBER_INSURANCE", "Киберстрахование", "Cyber insurance"),
    ("INSURANCE", "MORTGAGE_INSURANCE", "Ипотечное страхование", "Mortgage insurance"),
    ("CRYPTO_WEB3", "CRYPTO_EXCHANGES", "Криптобиржи", "Crypto exchanges"),
    ("CRYPTO_WEB3", "CRYPTO_WALLETS", "Криптокошельки", "Crypto wallets"),
    ("CRYPTO_WEB3", "CRYPTO_PAYMENTS", "Криптоплатежи", "Crypto payments"),
    ("CRYPTO_WEB3", "CRYPTO_CARDS", "Криптокарты", "Crypto cards"),
    ("CRYPTO_WEB3", "DEFI", "DeFi", "DeFi"),
    ("CRYPTO_WEB3", "STAKING", "Стейкинг", "Staking"),
    ("CRYPTO_WEB3", "CRYPTO_LENDING", "Криптокредитование", "Crypto lending"),
    ("CRYPTO_WEB3", "CRYPTO_TRADING", "Криптотрейдинг", "Crypto trading"),
    ("CRYPTO_WEB3", "CRYPTO_ANALYTICS", "Криптоаналитика", "Crypto analytics"),
    ("CRYPTO_WEB3", "NFT_PLATFORMS", "NFT-платформы", "NFT platforms"),
    ("CRYPTO_WEB3", "MINING_SERVICES", "Майнинг", "Mining"),
    ("CRYPTO_WEB3", "BLOCKCHAIN_INFRASTRUCTURE", "Blockchain-инфраструктура", "Blockchain infrastructure"),
    ("CRYPTO_WEB3", "WEB3_APPS", "Web3-приложения", "Web3 apps"),
    ("RETAIL", "GENERAL_ONLINE_STORES", "Универсальные интернет-магазины", "General online stores"),
    ("RETAIL", "GENERAL_MARKETPLACES", "Маркетплейсы", "Marketplaces"),
    ("RETAIL", "GIFTS", "Подарки", "Gifts"),
    ("RETAIL", "HOBBY_CRAFTS", "Хобби и рукоделие", "Hobby & crafts"),
    ("RETAIL", "COLLECTIBLES", "Коллекционирование", "Collectibles"),
    ("RETAIL", "LUXURY_GOODS", "Товары класса люкс", "Luxury goods"),
    ("RETAIL", "SECOND_HAND", "Секонд-хенд", "Second-hand"),
    ("RETAIL", "REFURBISHED_GOODS", "Восстановленные товары", "Refurbished goods"),
    ("RETAIL", "OFFICE_SUPPLIES", "Канцелярия", "Office supplies"),
    ("RETAIL", "FLOWERS", "Цветы", "Flowers"),
    ("FASHION", "WOMENS_CLOTHING", "Женская одежда", "Women's clothing"),
    ("FASHION", "MENS_CLOTHING", "Мужская одежда", "Men's clothing"),
    ("FASHION", "FOOTWEAR", "Обувь", "Footwear"),
    ("FASHION", "SPORTSWEAR", "Спортивная одежда", "Sportswear"),
    ("FASHION", "UNDERWEAR", "Бельё", "Underwear"),
    ("FASHION", "BAGS", "Сумки", "Bags"),
    ("FASHION", "FASHION_ACCESSORIES", "Модные аксессуары", "Fashion accessories"),
    ("FASHION", "JEWELRY", "Ювелирные изделия", "Jewelry"),
    ("FASHION", "WATCHES", "Часы", "Watches"),
    ("FASHION", "EYEWEAR", "Очки", "Eyewear"),
    ("FASHION", "STREETWEAR", "Стритвир", "Streetwear"),
    ("FASHION", "WORKWEAR", "Спецодежда", "Workwear"),
    ("BEAUTY", "COSMETICS", "Косметика", "Cosmetics"),
    ("BEAUTY", "PERFUMERY", "Парфюмерия", "Perfumery"),
    ("BEAUTY", "SKINCARE", "Уход за кожей", "Skincare"),
    ("BEAUTY", "BODY_CARE", "Уход за телом", "Body care"),
    ("BEAUTY", "HAIR_CARE", "Уход за волосами", "Hair care"),
    ("BEAUTY", "PROFESSIONAL_COSMETICS", "Профессиональная косметика", "Professional cosmetics"),
    ("BEAUTY", "BEAUTY_DEVICES", "Приборы для красоты", "Beauty devices"),
    ("BEAUTY", "BEAUTY_SALONS", "Салоны красоты", "Beauty salons"),
    ("BEAUTY", "COSMETOLOGY", "Косметология", "Cosmetology"),
    ("BEAUTY", "NAIL_SERVICES", "Ногтевой сервис", "Nail services"),
    ("BEAUTY", "BARBER_SERVICES", "Барбершопы", "Barber services"),
    ("ELECTRONICS", "SMARTPHONES", "Смартфоны", "Smartphones"),
    ("ELECTRONICS", "LAPTOPS", "Ноутбуки", "Laptops"),
    ("ELECTRONICS", "DESKTOP_COMPUTERS", "Настольные компьютеры", "Desktop computers"),
    ("ELECTRONICS", "PC_COMPONENTS", "Комплектующие", "PC components"),
    ("ELECTRONICS", "TABLETS", "Планшеты", "Tablets"),
    ("ELECTRONICS", "TV", "Телевизоры", "TVs"),
    ("ELECTRONICS", "AUDIO_EQUIPMENT", "Аудиотехника", "Audio equipment"),
    ("ELECTRONICS", "HEADPHONES", "Наушники", "Headphones"),
    ("ELECTRONICS", "CAMERAS", "Фото- и видеокамеры", "Cameras"),
    ("ELECTRONICS", "WEARABLES", "Носимая электроника", "Wearables"),
    ("ELECTRONICS", "GAMING_HARDWARE", "Игровое железо", "Gaming hardware"),
    ("ELECTRONICS", "DRONES", "Дроны", "Drones"),
    ("ELECTRONICS", "ELECTRONIC_ACCESSORIES", "Электронные аксессуары", "Electronic accessories"),
    ("HEALTH", "CLINICS", "Клиники", "Clinics"),
    ("HEALTH", "MEDICAL_CENTERS", "Медицинские центры", "Medical centers"),
    ("HEALTH", "TELEMEDICINE", "Телемедицина", "Telemedicine"),
    ("HEALTH", "DIAGNOSTICS", "Диагностика", "Diagnostics"),
    ("HEALTH", "LAB_TESTS", "Лабораторные анализы", "Lab tests"),
    ("HEALTH", "DENTISTRY", "Стоматология", "Dentistry"),
    ("HEALTH", "OPHTHALMOLOGY", "Офтальмология", "Ophthalmology"),
    ("HEALTH", "REPRODUCTIVE_MEDICINE", "Репродуктивная медицина", "Reproductive medicine"),
    ("HEALTH", "PHYSIOTHERAPY", "Физиотерапия", "Physiotherapy"),
    ("HEALTH", "REHABILITATION", "Реабилитация", "Rehabilitation"),
    ("HEALTH", "MENTAL_HEALTH", "Ментальное здоровье", "Mental health"),
    ("HEALTH", "PHARMACIES", "Аптеки", "Pharmacies"),
    ("HEALTH", "MEDICAL_EQUIPMENT", "Медицинское оборудование", "Medical equipment"),
    ("HEALTH", "MEDICAL_CHECKUPS", "Чекапы", "Medical checkups"),
    ("NUTRA", "VITAMINS", "Витамины", "Vitamins"),
    ("NUTRA", "MINERALS", "Минералы", "Minerals"),
    ("NUTRA", "DIETARY_SUPPLEMENTS", "БАД", "Dietary supplements"),
    ("NUTRA", "SPORTS_SUPPLEMENTS", "Спортивное питание", "Sports supplements"),
    ("NUTRA", "PROTEIN", "Протеин", "Protein"),
    ("NUTRA", "JOINT_SUPPLEMENTS", "Для суставов", "Joint supplements"),
    ("NUTRA", "SLEEP_SUPPLEMENTS", "Для сна", "Sleep supplements"),
    ("NUTRA", "IMMUNITY_SUPPLEMENTS", "Для иммунитета", "Immunity supplements"),
    ("NUTRA", "DIGESTION_SUPPLEMENTS", "Для пищеварения", "Digestion supplements"),
    ("NUTRA", "BEAUTY_SUPPLEMENTS", "Для красоты", "Beauty supplements"),
    ("NUTRA", "WEIGHT_MANAGEMENT", "Контроль веса", "Weight management"),
    ("NUTRA", "MENS_SUPPLEMENTS", "Для мужчин", "Men's supplements"),
    ("NUTRA", "WOMENS_SUPPLEMENTS", "Для женщин", "Women's supplements"),
    ("NUTRA", "HERBAL_PRODUCTS", "Растительные препараты", "Herbal products"),
    ("SPORTS_FITNESS", "FITNESS_CLUBS", "Фитнес-клубы", "Fitness clubs"),
    ("SPORTS_FITNESS", "ONLINE_FITNESS", "Онлайн-фитнес", "Online fitness"),
    ("SPORTS_FITNESS", "PERSONAL_TRAINING", "Персональные тренировки", "Personal training"),
    ("SPORTS_FITNESS", "YOGA", "Йога", "Yoga"),
    ("SPORTS_FITNESS", "PILATES", "Пилатес", "Pilates"),
    ("SPORTS_FITNESS", "RUNNING_SERVICES", "Бег", "Running"),
    ("SPORTS_FITNESS", "CYCLING_SERVICES", "Велоспорт", "Cycling"),
    ("SPORTS_FITNESS", "SWIMMING_SERVICES", "Плавание", "Swimming"),
    ("SPORTS_FITNESS", "COMBAT_SPORTS", "Единоборства", "Combat sports"),
    ("SPORTS_FITNESS", "FITNESS_APPS", "Фитнес-приложения", "Fitness apps"),
    ("SPORTS_FITNESS", "FITNESS_EQUIPMENT", "Фитнес-оборудование", "Fitness equipment"),
    ("SPORTS_FITNESS", "SPORTING_GOODS", "Спортивные товары", "Sporting goods"),
    ("EDUCATION", "ONLINE_COURSES", "Онлайн-курсы", "Online courses"),
    ("EDUCATION", "VOCATIONAL_EDUCATION", "Профессиональное образование", "Vocational education"),
    ("EDUCATION", "HIGHER_EDUCATION", "Высшее образование", "Higher education"),
    ("EDUCATION", "COLLEGES", "Колледжи", "Colleges"),
    ("EDUCATION", "SCHOOLS", "Школы", "Schools"),
    ("EDUCATION", "PROGRAMMING_EDUCATION", "Обучение программированию", "Programming education"),
    ("EDUCATION", "DATA_SCIENCE_EDUCATION", "Data Science", "Data science education"),
    ("EDUCATION", "AI_EDUCATION", "Обучение AI", "AI education"),
    ("EDUCATION", "DESIGN_EDUCATION", "Дизайн", "Design education"),
    ("EDUCATION", "MARKETING_EDUCATION", "Маркетинг", "Marketing education"),
    ("EDUCATION", "MANAGEMENT_EDUCATION", "Менеджмент", "Management education"),
    ("EDUCATION", "SALES_EDUCATION", "Продажи", "Sales education"),
    ("EDUCATION", "FINANCE_EDUCATION", "Финансы", "Finance education"),
    ("EDUCATION", "LANGUAGE_COURSES", "Языковые курсы", "Language courses"),
    ("EDUCATION", "ENGLISH_COURSES", "Английский язык", "English courses"),
    ("EDUCATION", "TUTORING", "Репетиторство", "Tutoring"),
    ("EDUCATION", "EXAM_PREPARATION", "Подготовка к экзаменам", "Exam preparation"),
    ("EDUCATION", "CHILDRENS_EDUCATION", "Детское образование", "Children's education"),
    ("EDUCATION", "CORPORATE_EDUCATION", "Корпоративное обучение", "Corporate education"),
    ("EDUCATION", "PROFESSIONAL_CERTIFICATION", "Профессиональная сертификация", "Professional certification"),
    ("EDUCATION", "SOFT_SKILLS_EDUCATION", "Soft skills", "Soft skills education"),
    ("EDUCATION", "MBA", "MBA", "MBA"),
    ("EDUCATION", "MUSIC_EDUCATION", "Музыкальное образование", "Music education"),
    ("EDUCATION", "CREATIVE_EDUCATION", "Творческое образование", "Creative education"),
    ("HR_JOBS", "JOB_BOARDS", "Доски вакансий", "Job boards"),
    ("HR_JOBS", "RECRUITMENT", "Рекрутинг", "Recruitment"),
    ("HR_JOBS", "EXECUTIVE_SEARCH", "Executive search", "Executive search"),
    ("HR_JOBS", "STAFFING", "Аутстаффинг", "Staffing"),
    ("HR_JOBS", "FREELANCE_PLATFORMS", "Фриланс-платформы", "Freelance platforms"),
    ("HR_JOBS", "GIG_WORK", "Гиг-работа", "Gig work"),
    ("HR_JOBS", "INTERNSHIPS", "Стажировки", "Internships"),
    ("HR_JOBS", "CAREER_COACHING", "Карьерный коучинг", "Career coaching"),
    ("HR_JOBS", "RESUME_SERVICES", "Резюме", "Resume services"),
    ("HR_JOBS", "ATS", "ATS", "ATS"),
    ("HR_JOBS", "HRM", "HRM", "HRM"),
    ("HR_JOBS", "PAYROLL_HR", "Кадровый учёт и зарплата", "Payroll HR"),
    ("HR_JOBS", "EMPLOYEE_BENEFITS", "Льготы сотрудникам", "Employee benefits"),
    ("HR_JOBS", "ASSESSMENT_SERVICES", "Оценка персонала", "Assessment services"),
    ("HR_JOBS", "BACKGROUND_CHECKS", "Проверки кандидатов", "Background checks"),
    ("SAAS", "CRM", "CRM", "CRM"),
    ("SAAS", "ERP", "ERP", "ERP"),
    ("SAAS", "PROJECT_MANAGEMENT", "Управление проектами", "Project management"),
    ("SAAS", "TASK_MANAGEMENT", "Управление задачами", "Task management"),
    ("SAAS", "COLLABORATION_SOFTWARE", "Совместная работа", "Collaboration software"),
    ("SAAS", "VIDEO_CONFERENCING", "Видеоконференции", "Video conferencing"),
    ("SAAS", "HELPDESK", "Helpdesk", "Helpdesk"),
    ("SAAS", "CUSTOMER_SUCCESS_SOFTWARE", "Customer success", "Customer success software"),
    ("SAAS", "ACCOUNTING_SOFTWARE", "Бухгалтерия", "Accounting software"),
    ("SAAS", "SALES_SOFTWARE", "Продажи", "Sales software"),
    ("SAAS", "BUSINESS_ANALYTICS", "Бизнес-аналитика", "Business analytics"),
    ("SAAS", "AI_TOOLS", "AI-инструменты", "AI tools"),
    ("SAAS", "GENERATIVE_AI", "Генеративный AI", "Generative AI"),
    ("SAAS", "DEVELOPER_TOOLS", "Инструменты разработчика", "Developer tools"),
    ("SAAS", "IDE_TOOLS", "IDE", "IDE tools"),
    ("SAAS", "API_PLATFORMS", "API-платформы", "API platforms"),
    ("SAAS", "NO_CODE", "No-code", "No-code"),
    ("SAAS", "LOW_CODE", "Low-code", "Low-code"),
    ("SAAS", "DOCUMENT_MANAGEMENT", "Документооборот", "Document management"),
    ("SAAS", "E_SIGNATURE", "Электронная подпись", "E-signature"),
    ("SAAS", "PRODUCTIVITY_SOFTWARE", "Продуктивность", "Productivity software"),
    ("SAAS", "OFFICE_SOFTWARE", "Офисное ПО", "Office software"),
    ("SAAS", "WEBSITE_BUILDERS", "Конструкторы сайтов", "Website builders"),
    ("SAAS", "CMS", "CMS", "CMS"),
    ("SAAS", "ECOMMERCE_PLATFORMS", "E-commerce платформы", "Ecommerce platforms"),
    ("SAAS", "DESIGN_SOFTWARE", "Дизайн", "Design software"),
    ("SAAS", "VIDEO_SOFTWARE", "Видео", "Video software"),
    ("SAAS", "AUDIO_SOFTWARE", "Аудио", "Audio software"),
    ("CYBERSECURITY", "ANTIVIRUS", "Антивирусы", "Antivirus"),
    ("CYBERSECURITY", "ENDPOINT_PROTECTION", "Защита конечных точек", "Endpoint protection"),
    ("CYBERSECURITY", "VPN", "VPN", "VPN"),
    ("CYBERSECURITY", "PASSWORD_MANAGERS", "Менеджеры паролей", "Password managers"),
    ("CYBERSECURITY", "DLP", "DLP", "DLP"),
    ("CYBERSECURITY", "SIEM", "SIEM", "SIEM"),
    ("CYBERSECURITY", "SOC_SERVICES", "SOC", "SOC services"),
    ("CYBERSECURITY", "VULNERABILITY_MANAGEMENT", "Управление уязвимостями", "Vulnerability management"),
    ("CYBERSECURITY", "PENETRATION_TESTING", "Пентесты", "Penetration testing"),
    ("CYBERSECURITY", "CLOUD_SECURITY", "Облачная безопасность", "Cloud security"),
    ("CYBERSECURITY", "EMAIL_SECURITY", "Безопасность почты", "Email security"),
    ("CYBERSECURITY", "ANTI_FRAUD", "Антифрод", "Anti-fraud"),
    ("CYBERSECURITY", "IDENTITY_VERIFICATION", "Верификация личности", "Identity verification"),
    ("CYBERSECURITY", "KYC_SERVICES", "KYC", "KYC services"),
    ("CYBERSECURITY", "CYBERSECURITY_TRAINING", "Обучение кибербезопасности", "Cybersecurity training"),
    ("HOSTING_INFRA", "WEB_HOSTING", "Веб-хостинг", "Web hosting"),
    ("HOSTING_INFRA", "VPS_VDS", "VPS/VDS", "VPS/VDS"),
    ("HOSTING_INFRA", "DEDICATED_SERVERS", "Выделенные серверы", "Dedicated servers"),
    ("HOSTING_INFRA", "CLOUD_COMPUTE", "Облачные вычисления", "Cloud compute"),
    ("HOSTING_INFRA", "KUBERNETES_HOSTING", "Kubernetes-хостинг", "Kubernetes hosting"),
    ("HOSTING_INFRA", "DOMAINS", "Домены", "Domains"),
    ("HOSTING_INFRA", "SSL_CERTIFICATES", "SSL-сертификаты", "SSL certificates"),
    ("HOSTING_INFRA", "CDN", "CDN", "CDN"),
    ("HOSTING_INFRA", "DNS_SERVICES", "DNS", "DNS services"),
    ("HOSTING_INFRA", "OBJECT_STORAGE", "Объектное хранилище", "Object storage"),
    ("HOSTING_INFRA", "BACKUP_SERVICES", "Резервное копирование", "Backup services"),
    ("HOSTING_INFRA", "COLOCATION", "Колокация", "Colocation"),
    ("HOSTING_INFRA", "MANAGED_INFRASTRUCTURE", "Управляемая инфраструктура", "Managed infrastructure"),
    ("HOSTING_INFRA", "DATABASE_HOSTING", "Хостинг баз данных", "Database hosting"),
    ("HOSTING_INFRA", "EMAIL_HOSTING", "Почтовый хостинг", "Email hosting"),
    ("MARKETING_ADTECH", "CONTEXTUAL_ADVERTISING_SERVICES", "Контекстная реклама", "Contextual advertising"),
    ("MARKETING_ADTECH", "TARGETED_ADVERTISING_SERVICES", "Таргетированная реклама", "Targeted advertising"),
    ("MARKETING_ADTECH", "PROGRAMMATIC_PLATFORMS", "Programmatic", "Programmatic platforms"),
    ("MARKETING_ADTECH", "DISPLAY_ADVERTISING", "Медийная реклама", "Display advertising"),
    ("MARKETING_ADTECH", "NATIVE_ADVERTISING", "Нативная реклама", "Native advertising"),
    ("MARKETING_ADTECH", "AFFILIATE_PLATFORMS", "Партнёрские платформы", "Affiliate platforms"),
    ("MARKETING_ADTECH", "INFLUENCER_MARKETING", "Инфлюенс-маркетинг", "Influencer marketing"),
    ("MARKETING_ADTECH", "SEO_SERVICES", "SEO", "SEO services"),
    ("MARKETING_ADTECH", "ASO_SERVICES", "ASO", "ASO services"),
    ("MARKETING_ADTECH", "EMAIL_MARKETING_SERVICES", "Email-маркетинг", "Email marketing"),
    ("MARKETING_ADTECH", "MARKETING_AUTOMATION", "Маркетинговая автоматизация", "Marketing automation"),
    ("MARKETING_ADTECH", "ADTECH", "AdTech", "AdTech"),
    ("MARKETING_ADTECH", "MARKETING_ANALYTICS", "Маркетинговая аналитика", "Marketing analytics"),
    ("MARKETING_ADTECH", "CALL_TRACKING", "Коллтрекинг", "Call tracking"),
    ("MARKETING_ADTECH", "ATTRIBUTION_SOFTWARE", "Атрибуция", "Attribution software"),
    ("MARKETING_ADTECH", "LEAD_GENERATION_SERVICES", "Лидогенерация", "Lead generation"),
    ("MARKETING_ADTECH", "CONTENT_MARKETING", "Контент-маркетинг", "Content marketing"),
    ("MARKETING_ADTECH", "PR_SERVICES", "PR", "PR services"),
    ("MARKETING_ADTECH", "REPUTATION_MANAGEMENT", "Управление репутацией", "Reputation management"),
    ("B2B_SERVICES", "BUSINESS_CONSULTING", "Бизнес-консалтинг", "Business consulting"),
    ("B2B_SERVICES", "IT_CONSULTING", "IT-консалтинг", "IT consulting"),
    ("B2B_SERVICES", "AUDIT_SERVICES", "Аудит", "Audit"),
    ("B2B_SERVICES", "ACCOUNTING_SERVICES", "Бухгалтерские услуги", "Accounting services"),
    ("B2B_SERVICES", "TAX_SERVICES", "Налоги", "Tax services"),
    ("B2B_SERVICES", "IT_OUTSOURCING", "IT-аутсорсинг", "IT outsourcing"),
    ("B2B_SERVICES", "DEVELOPMENT_SERVICES", "Разработка", "Development services"),
    ("B2B_SERVICES", "DESIGN_SERVICES", "Дизайн-услуги", "Design services"),
    ("B2B_SERVICES", "CALL_CENTER_OUTSOURCING", "Колл-центры", "Call center outsourcing"),
    ("B2B_SERVICES", "CUSTOMER_SUPPORT_OUTSOURCING", "Поддержка клиентов", "Customer support outsourcing"),
    ("B2B_SERVICES", "SALES_OUTSOURCING", "Аутсорсинг продаж", "Sales outsourcing"),
    ("B2B_SERVICES", "RESEARCH_SERVICES", "Исследования", "Research services"),
    ("B2B_SERVICES", "TRANSLATION_SERVICES", "Переводы", "Translation services"),
    ("TELECOM", "MOBILE_OPERATORS", "Мобильные операторы", "Mobile operators"),
    ("TELECOM", "SIM_CARDS", "SIM-карты", "SIM cards"),
    ("TELECOM", "ESIM", "eSIM", "eSIM"),
    ("TELECOM", "HOME_INTERNET", "Домашний интернет", "Home internet"),
    ("TELECOM", "MOBILE_INTERNET", "Мобильный интернет", "Mobile internet"),
    ("TELECOM", "VOIP", "VoIP", "VoIP"),
    ("TELECOM", "VIRTUAL_PBX", "Виртуальная АТС", "Virtual PBX"),
    ("TELECOM", "BUSINESS_TELECOM", "Бизнес-телеком", "Business telecom"),
    ("TELECOM", "ROAMING", "Роуминг", "Roaming"),
    ("TELECOM", "INTERNATIONAL_CALLS", "Международные звонки", "International calls"),
    ("GAMING", "PC_GAMES", "PC-игры", "PC games"),
    ("GAMING", "CONSOLE_GAMES", "Консольные игры", "Console games"),
    ("GAMING", "MOBILE_GAMES", "Мобильные игры", "Mobile games"),
    ("GAMING", "BROWSER_GAMES", "Браузерные игры", "Browser games"),
    ("GAMING", "CLOUD_GAMING", "Облачный гейминг", "Cloud gaming"),
    ("GAMING", "GAME_SUBSCRIPTIONS", "Игровые подписки", "Game subscriptions"),
    ("GAMING", "GAME_STORES", "Игровые магазины", "Game stores"),
    ("GAMING", "IN_GAME_ITEMS", "Внутриигровые предметы", "In-game items"),
    ("GAMING", "GAME_CURRENCY", "Игровая валюта", "Game currency"),
    ("GAMING", "ESPORTS_PLATFORMS", "Киберспорт", "Esports platforms"),
    ("GAMING", "GAME_STREAMING", "Игровой стриминг", "Game streaming"),
    ("IGAMING", "ONLINE_CASINO", "Онлайн-казино", "Online casino"),
    ("IGAMING", "SLOTS", "Слоты", "Slots"),
    ("IGAMING", "LIVE_CASINO", "Live-казино", "Live casino"),
    ("IGAMING", "SPORTSBOOK", "Ставки на спорт", "Sportsbook"),
    ("IGAMING", "ESPORTS_BETTING", "Ставки на киберспорт", "Esports betting"),
    ("IGAMING", "POKER", "Покер", "Poker"),
    ("IGAMING", "BINGO", "Бинго", "Bingo"),
    ("IGAMING", "LOTTERY", "Лотереи", "Lottery"),
    ("IGAMING", "FANTASY_SPORTS", "Фэнтези-спорт", "Fantasy sports"),
    ("IGAMING", "SOCIAL_CASINO", "Social casino", "Social casino"),
    ("IGAMING", "PREDICTION_PLATFORMS", "Платформы прогнозов", "Prediction platforms"),
    ("DATING", "GENERAL_DATING", "Знакомства", "General dating"),
    ("DATING", "SERIOUS_DATING", "Серьёзные отношения", "Serious dating"),
    ("DATING", "CASUAL_DATING", "Casual-знакомства", "Casual dating"),
    ("DATING", "INTERNATIONAL_DATING", "Международные знакомства", "International dating"),
    ("DATING", "SENIOR_DATING", "Знакомства для старшего возраста", "Senior dating"),
    ("DATING", "NICHE_DATING", "Нишевые знакомства", "Niche dating"),
    ("DATING", "MATCHMAKING", "Сватовство", "Matchmaking"),
    ("ADULT", "ADULT_CONTENT", "Adult-контент", "Adult content"),
    ("ADULT", "ADULT_DATING", "Adult-знакомства", "Adult dating"),
    ("ADULT", "ADULT_STREAMING", "Adult-стриминг", "Adult streaming"),
    ("ADULT", "ADULT_COMMUNITIES", "Adult-сообщества", "Adult communities"),
    ("ADULT", "CREATOR_ADULT_PLATFORMS", "Adult-платформы для авторов", "Creator adult platforms"),
    ("TRAVEL", "HOTELS", "Отели", "Hotels"),
    ("TRAVEL", "APARTMENTS", "Апартаменты", "Apartments"),
    ("TRAVEL", "HOSTELS", "Хостелы", "Hostels"),
    ("TRAVEL", "VACATION_RENTALS", "Посуточная аренда", "Vacation rentals"),
    ("TRAVEL", "FLIGHTS", "Авиабилеты", "Flights"),
    ("TRAVEL", "RAIL_TICKETS", "Ж/д билеты", "Rail tickets"),
    ("TRAVEL", "BUS_TICKETS", "Автобусные билеты", "Bus tickets"),
    ("TRAVEL", "CRUISES", "Круизы", "Cruises"),
    ("TRAVEL", "PACKAGE_TOURS", "Пакетные туры", "Package tours"),
    ("TRAVEL", "TOURS", "Туры", "Tours"),
    ("TRAVEL", "EXCURSIONS", "Экскурсии", "Excursions"),
    ("TRAVEL", "TRAVEL_ACTIVITIES", "Активности в поездках", "Travel activities"),
    ("TRAVEL", "CAR_RENTAL", "Аренда авто", "Car rental"),
    ("TRAVEL", "TRANSFERS", "Трансферы", "Transfers"),
    ("TRAVEL", "BUSINESS_TRAVEL", "Деловые поездки", "Business travel"),
    ("AUTOMOTIVE", "NEW_CARS", "Новые автомобили", "New cars"),
    ("AUTOMOTIVE", "USED_CARS", "Автомобили с пробегом", "Used cars"),
    ("AUTOMOTIVE", "AUTO_CLASSIFIEDS", "Автообъявления", "Auto classifieds"),
    ("AUTOMOTIVE", "AUTO_PARTS", "Автозапчасти", "Auto parts"),
    ("AUTOMOTIVE", "TIRES", "Шины", "Tires"),
    ("AUTOMOTIVE", "WHEELS", "Диски", "Wheels"),
    ("AUTOMOTIVE", "AUTO_ACCESSORIES", "Автоаксессуары", "Auto accessories"),
    ("AUTOMOTIVE", "AUTO_SERVICE", "Автосервис", "Auto service"),
    ("AUTOMOTIVE", "AUTO_REPAIR", "Авторемонт", "Auto repair"),
    ("AUTOMOTIVE", "AUTO_MAINTENANCE", "Техобслуживание", "Auto maintenance"),
    ("AUTOMOTIVE", "CAR_WASH", "Автомойки", "Car wash"),
    ("AUTOMOTIVE", "DETAILING", "Детейлинг", "Detailing"),
    ("AUTOMOTIVE", "ROADSIDE_ASSISTANCE", "Помощь на дороге", "Roadside assistance"),
    ("AUTOMOTIVE", "FUEL_SERVICES", "Топливо", "Fuel services"),
    ("AUTOMOTIVE", "CAR_SHARING", "Каршеринг", "Car sharing"),
    ("REAL_ESTATE", "NEW_DEVELOPMENTS", "Новостройки", "New developments"),
    ("REAL_ESTATE", "RESALE_PROPERTY", "Вторичная недвижимость", "Resale property"),
    ("REAL_ESTATE", "APARTMENT_RENTAL", "Аренда квартир", "Apartment rental"),
    ("REAL_ESTATE", "HOUSE_RENTAL", "Аренда домов", "House rental"),
    ("REAL_ESTATE", "COMMERCIAL_REAL_ESTATE", "Коммерческая недвижимость", "Commercial real estate"),
    ("REAL_ESTATE", "COUNTRY_PROPERTY", "Загородная недвижимость", "Country property"),
    ("REAL_ESTATE", "LAND", "Земельные участки", "Land"),
    ("REAL_ESTATE", "OVERSEAS_PROPERTY", "Зарубежная недвижимость", "Overseas property"),
    ("REAL_ESTATE", "PROPERTY_MANAGEMENT", "Управление недвижимостью", "Property management"),
    ("REAL_ESTATE", "REAL_ESTATE_AGENCIES", "Агентства недвижимости", "Real estate agencies"),
    ("REAL_ESTATE", "PROPERTY_DEVELOPERS", "Девелоперы", "Property developers"),
    ("REAL_ESTATE", "CO_LIVING", "Коливинг", "Co-living"),
    ("REAL_ESTATE", "SELF_STORAGE", "Self storage", "Self storage"),
    ("HOME_FURNITURE", "FURNITURE", "Мебель", "Furniture"),
    ("HOME_FURNITURE", "MATTRESSES", "Матрасы", "Mattresses"),
    ("HOME_FURNITURE", "LIGHTING", "Освещение", "Lighting"),
    ("HOME_FURNITURE", "HOME_DECOR", "Декор", "Home decor"),
    ("HOME_FURNITURE", "HOME_TEXTILES", "Текстиль", "Home textiles"),
    ("HOME_FURNITURE", "TABLEWARE", "Посуда", "Tableware"),
    ("HOME_FURNITURE", "KITCHEN_FURNITURE", "Кухонная мебель", "Kitchen furniture"),
    ("HOME_FURNITURE", "BATHROOM_FURNITURE", "Мебель для ванной", "Bathroom furniture"),
    ("HOME_FURNITURE", "HOME_STORAGE", "Хранение", "Home storage"),
    ("HOME_FURNITURE", "HOUSEHOLD_GOODS", "Товары для дома", "Household goods"),
    ("HOME_FURNITURE", "SMART_HOME_DEVICES", "Умный дом", "Smart home devices"),
    ("HOME_FURNITURE", "GARDEN_FURNITURE", "Садовая мебель", "Garden furniture"),
    ("CONSTRUCTION_REPAIR", "BUILDING_MATERIALS", "Стройматериалы", "Building materials"),
    ("CONSTRUCTION_REPAIR", "TOOLS", "Инструменты", "Tools"),
    ("CONSTRUCTION_REPAIR", "APARTMENT_RENOVATION", "Ремонт квартир", "Apartment renovation"),
    ("CONSTRUCTION_REPAIR", "HOUSE_CONSTRUCTION", "Строительство домов", "House construction"),
    ("CONSTRUCTION_REPAIR", "INTERIOR_DESIGN", "Дизайн интерьера", "Interior design"),
    ("CONSTRUCTION_REPAIR", "ARCHITECTURE_SERVICES", "Архитектура", "Architecture services"),
    ("CONSTRUCTION_REPAIR", "PLUMBING_PRODUCTS", "Сантехника", "Plumbing products"),
    ("CONSTRUCTION_REPAIR", "ELECTRICAL_PRODUCTS", "Электрика", "Electrical products"),
    ("CONSTRUCTION_REPAIR", "WINDOWS", "Окна", "Windows"),
    ("CONSTRUCTION_REPAIR", "DOORS", "Двери", "Doors"),
    ("CONSTRUCTION_REPAIR", "FLOORING", "Напольные покрытия", "Flooring"),
    ("CONSTRUCTION_REPAIR", "PAINT_COATINGS", "Краски и покрытия", "Paint & coatings"),
    ("CONSTRUCTION_REPAIR", "ROOFING", "Кровля", "Roofing"),
    ("CONSTRUCTION_REPAIR", "HVAC", "HVAC", "HVAC"),
    ("CONSTRUCTION_REPAIR", "HEATING", "Отопление", "Heating"),
    ("CONSTRUCTION_REPAIR", "VENTILATION", "Вентиляция", "Ventilation"),
    ("CONSTRUCTION_REPAIR", "SMART_HOME_INSTALLATION", "Установка умного дома", "Smart home installation"),
    ("HOME_SERVICES", "CLEANING_SERVICES", "Клининг", "Cleaning services"),
    ("HOME_SERVICES", "APPLIANCE_REPAIR", "Ремонт техники", "Appliance repair"),
    ("HOME_SERVICES", "PLUMBING_SERVICES", "Сантехнические услуги", "Plumbing services"),
    ("HOME_SERVICES", "ELECTRICIAN_SERVICES", "Услуги электрика", "Electrician services"),
    ("HOME_SERVICES", "HANDYMAN", "Мастер на час", "Handyman"),
    ("HOME_SERVICES", "PEST_CONTROL", "Дезинсекция", "Pest control"),
    ("HOME_SERVICES", "HOME_MOVING", "Переезды", "Home moving"),
    ("HOME_SERVICES", "GARDENING_SERVICES", "Садовники", "Gardening services"),
    ("HOME_SERVICES", "LANDSCAPING", "Ландшафт", "Landscaping"),
    ("HOME_SERVICES", "LOCKSMITH", "Вскрытие замков", "Locksmith"),
    ("HOME_SERVICES", "APPLIANCE_INSTALLATION", "Установка техники", "Appliance installation"),
    ("ENERGY", "ELECTRICITY_PROVIDERS", "Электроснабжение", "Electricity providers"),
    ("ENERGY", "GAS_PROVIDERS", "Газоснабжение", "Gas providers"),
    ("ENERGY", "SOLAR_PANELS", "Солнечные панели", "Solar panels"),
    ("ENERGY", "ENERGY_STORAGE", "Накопители энергии", "Energy storage"),
    ("ENERGY", "EV_CHARGING", "Зарядка электромобилей", "EV charging"),
    ("ENERGY", "ENERGY_EFFICIENCY", "Энергоэффективность", "Energy efficiency"),
    ("ENERGY", "SMART_METERS", "Умные счётчики", "Smart meters"),
    ("ENERGY", "GREEN_ENERGY", "Зелёная энергия", "Green energy"),
    ("FOOD_GROCERY", "GROCERIES", "Продукты", "Groceries"),
    ("FOOD_GROCERY", "FRESH_FOOD", "Свежие продукты", "Fresh food"),
    ("FOOD_GROCERY", "ORGANIC_FOOD", "Органические продукты", "Organic food"),
    ("FOOD_GROCERY", "MEAL_KITS", "Наборы еды", "Meal kits"),
    ("FOOD_GROCERY", "SPECIALTY_FOOD", "Специальные продукты", "Specialty food"),
    ("FOOD_GROCERY", "COFFEE", "Кофе", "Coffee"),
    ("FOOD_GROCERY", "TEA", "Чай", "Tea"),
    ("FOOD_GROCERY", "SNACKS", "Снеки", "Snacks"),
    ("FOOD_GROCERY", "BAKERY", "Выпечка", "Bakery"),
    ("FOOD_GROCERY", "FOOD_SUBSCRIPTIONS", "Продуктовые подписки", "Food subscriptions"),
    ("RESTAURANTS_DELIVERY", "RESTAURANTS", "Рестораны", "Restaurants"),
    ("RESTAURANTS_DELIVERY", "CAFES", "Кафе", "Cafes"),
    ("RESTAURANTS_DELIVERY", "FAST_FOOD", "Фастфуд", "Fast food"),
    ("RESTAURANTS_DELIVERY", "FOOD_DELIVERY", "Доставка еды", "Food delivery"),
    ("RESTAURANTS_DELIVERY", "RESTAURANT_BOOKING", "Бронирование столиков", "Restaurant booking"),
    ("RESTAURANTS_DELIVERY", "DARK_KITCHENS", "Dark kitchen", "Dark kitchens"),
    ("RESTAURANTS_DELIVERY", "CATERING", "Кейтеринг", "Catering"),
    ("RESTAURANTS_DELIVERY", "CORPORATE_CATERING", "Корпоративный кейтеринг", "Corporate catering"),
    ("LOGISTICS", "COURIER_SERVICES", "Курьерские услуги", "Courier services"),
    ("LOGISTICS", "LAST_MILE_DELIVERY", "Последняя миля", "Last-mile delivery"),
    ("LOGISTICS", "PARCEL_DELIVERY", "Доставка посылок", "Parcel delivery"),
    ("LOGISTICS", "INTERNATIONAL_DELIVERY", "Международная доставка", "International delivery"),
    ("LOGISTICS", "FREIGHT", "Грузоперевозки", "Freight"),
    ("LOGISTICS", "CARGO_TRANSPORTATION", "Транспортировка грузов", "Cargo transportation"),
    ("LOGISTICS", "FULFILLMENT", "Фулфилмент", "Fulfillment"),
    ("LOGISTICS", "WAREHOUSING", "Склады", "Warehousing"),
    ("LOGISTICS", "SHIPPING_PLATFORMS", "Платформы доставки", "Shipping platforms"),
    ("LOGISTICS", "POSTAL_SERVICES", "Почтовые услуги", "Postal services"),
    ("LEGAL", "LEGAL_CONSULTING", "Юридический консалтинг", "Legal consulting"),
    ("LEGAL", "FAMILY_LAW", "Семейное право", "Family law"),
    ("LEGAL", "CORPORATE_LAW", "Корпоративное право", "Corporate law"),
    ("LEGAL", "TAX_LAW", "Налоговое право", "Tax law"),
    ("LEGAL", "INTELLECTUAL_PROPERTY", "Интеллектуальная собственность", "Intellectual property"),
    ("LEGAL", "BANKRUPTCY", "Банкротство", "Bankruptcy"),
    ("LEGAL", "DEBT_COLLECTION", "Взыскание долгов", "Debt collection"),
    ("LEGAL", "LEGALTECH", "LegalTech", "LegalTech"),
    ("LEGAL", "LEGAL_DOCUMENTS", "Юридические документы", "Legal documents"),
    ("LEGAL", "COMPANY_REGISTRATION", "Регистрация компаний", "Company registration"),
    ("LEGAL", "TRADEMARK_REGISTRATION", "Регистрация товарных знаков", "Trademark registration"),
    ("IMMIGRATION_DOCUMENTS", "VISA_SERVICES", "Визы", "Visa services"),
    ("IMMIGRATION_DOCUMENTS", "IMMIGRATION_SERVICES", "Иммиграция", "Immigration services"),
    ("IMMIGRATION_DOCUMENTS", "RESIDENCE_PERMITS", "ВНЖ", "Residence permits"),
    ("IMMIGRATION_DOCUMENTS", "CITIZENSHIP_SERVICES", "Гражданство", "Citizenship services"),
    ("IMMIGRATION_DOCUMENTS", "MIGRATION_DOCUMENTS", "Миграционные документы", "Migration documents"),
    ("IMMIGRATION_DOCUMENTS", "NOTARY_SUPPORT", "Нотариальная поддержка", "Notary support"),
    ("IMMIGRATION_DOCUMENTS", "GOVERNMENT_APPLICATION_ASSISTANCE", "Помощь с госуслугами", "Government application assistance"),
    ("MEDIA_ENTERTAINMENT", "VIDEO_STREAMING", "Видеостриминг", "Video streaming"),
    ("MEDIA_ENTERTAINMENT", "MUSIC_STREAMING", "Музыкальный стриминг", "Music streaming"),
    ("MEDIA_ENTERTAINMENT", "SPORTS_STREAMING", "Спортивный стриминг", "Sports streaming"),
    ("MEDIA_ENTERTAINMENT", "NEWS_SUBSCRIPTIONS", "Новостные подписки", "News subscriptions"),
    ("MEDIA_ENTERTAINMENT", "DIGITAL_MAGAZINES", "Цифровые журналы", "Digital magazines"),
    ("MEDIA_ENTERTAINMENT", "PODCASTS", "Подкасты", "Podcasts"),
    ("MEDIA_ENTERTAINMENT", "EBOOKS", "Электронные книги", "E-books"),
    ("MEDIA_ENTERTAINMENT", "AUDIOBOOKS", "Аудиокниги", "Audiobooks"),
    ("MEDIA_ENTERTAINMENT", "CREATOR_SUBSCRIPTIONS", "Подписки на авторов", "Creator subscriptions"),
    ("MEDIA_ENTERTAINMENT", "ONLINE_CINEMA", "Онлайн-кинотеатры", "Online cinema"),
    ("EVENTS_TICKETS", "CONCERTS", "Концерты", "Concerts"),
    ("EVENTS_TICKETS", "THEATRE", "Театр", "Theatre"),
    ("EVENTS_TICKETS", "CINEMA_TICKETS", "Кинобилеты", "Cinema tickets"),
    ("EVENTS_TICKETS", "SPORTS_EVENTS", "Спортивные события", "Sports events"),
    ("EVENTS_TICKETS", "FESTIVALS", "Фестивали", "Festivals"),
    ("EVENTS_TICKETS", "CONFERENCES", "Конференции", "Conferences"),
    ("EVENTS_TICKETS", "BUSINESS_EVENTS", "Деловые события", "Business events"),
    ("EVENTS_TICKETS", "EXHIBITIONS", "Выставки", "Exhibitions"),
    ("EVENTS_TICKETS", "MUSEUMS", "Музеи", "Museums"),
    ("EVENTS_TICKETS", "ATTRACTIONS", "Достопримечательности", "Attractions"),
    ("EVENTS_TICKETS", "TICKET_PLATFORMS", "Билетные платформы", "Ticket platforms"),
    ("PETS", "PET_FOOD", "Корм для животных", "Pet food"),
    ("PETS", "PET_ACCESSORIES", "Зоотовары", "Pet accessories"),
    ("PETS", "VETERINARY_SERVICES", "Ветеринария", "Veterinary services"),
    ("PETS", "PET_GROOMING", "Груминг", "Pet grooming"),
    ("PETS", "PET_SITTING", "Передержка", "Pet sitting"),
    ("PETS", "PET_HOTELS", "Зоогостиницы", "Pet hotels"),
    ("PETS", "PET_TRAINING", "Дрессировка", "Pet training"),
    ("PETS", "PET_MARKETPLACES", "Зоомаркетплейсы", "Pet marketplaces"),
    ("PETS", "PET_HEALTH_PRODUCTS", "Здоровье животных", "Pet health products"),
    ("KIDS_FAMILY", "BABY_PRODUCTS", "Товары для малышей", "Baby products"),
    ("KIDS_FAMILY", "TOYS", "Игрушки", "Toys"),
    ("KIDS_FAMILY", "KIDS_CLOTHING", "Детская одежда", "Kids clothing"),
    ("KIDS_FAMILY", "BABY_FOOD", "Детское питание", "Baby food"),
    ("KIDS_FAMILY", "BABY_CARE", "Уход за детьми", "Baby care"),
    ("KIDS_FAMILY", "MATERNITY_PRODUCTS", "Товары для мам", "Maternity products"),
    ("KIDS_FAMILY", "BABYSITTING", "Няни", "Babysitting"),
    ("KIDS_FAMILY", "CHILDRENS_CAMPS", "Детские лагеря", "Children's camps"),
    ("KIDS_FAMILY", "FAMILY_SERVICES", "Семейные услуги", "Family services"),
    ("KIDS_FAMILY", "PARENTING_PLATFORMS", "Платформы для родителей", "Parenting platforms"),
    ("PHYSICAL_SECURITY", "ALARM_SYSTEMS", "Сигнализации", "Alarm systems"),
    ("PHYSICAL_SECURITY", "VIDEO_SURVEILLANCE", "Видеонаблюдение", "Video surveillance"),
    ("PHYSICAL_SECURITY", "ACCESS_CONTROL", "Контроль доступа", "Access control"),
    ("PHYSICAL_SECURITY", "SECURITY_SERVICES", "Охранные услуги", "Security services"),
    ("PHYSICAL_SECURITY", "HOME_SECURITY", "Безопасность дома", "Home security"),
    ("PHYSICAL_SECURITY", "BUSINESS_SECURITY", "Безопасность бизнеса", "Business security"),
    ("PHYSICAL_SECURITY", "PERSONAL_SECURITY", "Личная безопасность", "Personal security"),
    ("PRINT_PROMO", "PRINTING", "Полиграфия", "Printing"),
    ("PRINT_PROMO", "BUSINESS_CARDS", "Визитки", "Business cards"),
    ("PRINT_PROMO", "PACKAGING", "Упаковка", "Packaging"),
    ("PRINT_PROMO", "MERCHANDISE", "Мерч", "Merchandise"),
    ("PRINT_PROMO", "PROMOTIONAL_PRODUCTS", "Промопродукция", "Promotional products"),
    ("PRINT_PROMO", "CORPORATE_GIFTS", "Корпоративные подарки", "Corporate gifts"),
    ("PRINT_PROMO", "CUSTOM_BRANDED_APPAREL", "Брендированная одежда", "Custom branded apparel"),
    ("PRINT_PROMO", "SIGNAGE", "Вывески", "Signage"),
    ("INDUSTRIAL", "INDUSTRIAL_EQUIPMENT", "Промышленное оборудование", "Industrial equipment"),
    ("INDUSTRIAL", "MACHINERY", "Станки и машины", "Machinery"),
    ("INDUSTRIAL", "INDUSTRIAL_AUTOMATION", "Промышленная автоматизация", "Industrial automation"),
    ("INDUSTRIAL", "ROBOTICS", "Робототехника", "Robotics"),
    ("INDUSTRIAL", "INDUSTRIAL_COMPONENTS", "Комплектующие", "Industrial components"),
    ("INDUSTRIAL", "ELECTRICAL_EQUIPMENT", "Электрооборудование", "Electrical equipment"),
    ("INDUSTRIAL", "CONSTRUCTION_MACHINERY", "Строительная техника", "Construction machinery"),
    ("INDUSTRIAL", "RAW_MATERIALS", "Сырьё", "Raw materials"),
    ("INDUSTRIAL", "MANUFACTURING_SYSTEMS", "Производственные системы", "Manufacturing systems"),
    ("AGRICULTURE", "AGRICULTURAL_EQUIPMENT", "Сельхозтехника", "Agricultural equipment"),
    ("AGRICULTURE", "SEEDS", "Семена", "Seeds"),
    ("AGRICULTURE", "FERTILIZERS", "Удобрения", "Fertilizers"),
    ("AGRICULTURE", "FARM_SUPPLIES", "Товары для фермы", "Farm supplies"),
    ("AGRICULTURE", "AGROTECH", "Агротех", "Agrotech"),
    ("AGRICULTURE", "LIVESTOCK", "Животноводство", "Livestock"),
    ("AGRICULTURE", "AGRICULTURAL_MARKETPLACES", "Агромаркетплейсы", "Agricultural marketplaces"),
    ("AGRICULTURE", "FARM_MANAGEMENT", "Управление фермой", "Farm management"),
    ("SWEEPSTAKES_PROMOTIONS", "SWEEPSTAKES", "Розыгрыши", "Sweepstakes"),
    ("SWEEPSTAKES_PROMOTIONS", "PRIZE_DRAWS", "Призовые розыгрыши", "Prize draws"),
    ("SWEEPSTAKES_PROMOTIONS", "CONTESTS", "Конкурсы", "Contests"),
    ("SWEEPSTAKES_PROMOTIONS", "LOYALTY_PROMOTIONS", "Программы лояльности", "Loyalty promotions"),
    ("SWEEPSTAKES_PROMOTIONS", "PROMOTIONAL_COMPETITIONS", "Промо-конкурсы", "Promotional competitions"),
    ("CHARITY", "CHARITY_PLATFORMS", "Благотворительные платформы", "Charity platforms"),
    ("CHARITY", "DONATIONS", "Пожертвования", "Donations"),
    ("CHARITY", "NONPROFIT_FUNDRAISING", "Сбор средств НКО", "Nonprofit fundraising"),
    ("CHARITY", "CHARITY_CROWDFUNDING", "Благотворительный краудфандинг", "Charity crowdfunding"),
    ("OTHER", "OTHER", "Другое", "Other"),
]

LEGACY_CATEGORY_MAP = {
    "SaaS": "CRM",
    "Fintech": "PAYMENT_SERVICES",
    "Education": "ONLINE_COURSES",
    "E-commerce": "GENERAL_ONLINE_STORES",
    "Marketing": "CONTEXTUAL_ADVERTISING_SERVICES",
    "Other": "OTHER",
}

_VERTICAL_BY_CODE = {item[0]: item for item in VERTICALS}
_CATEGORY_BY_CODE = {item[1]: item for item in CATEGORIES}
_LEGACY_CATEGORY_LOWER = {key.lower(): value for key, value in LEGACY_CATEGORY_MAP.items()}


def category_belongs_to_unique_vertical() -> dict[str, str]:
    mapping: dict[str, str] = {}
    for vertical_code, category_code, _name_ru, _name_en in CATEGORIES:
        existing = mapping.get(category_code)
        if existing is not None and existing != vertical_code:
            raise ValueError(f"Category {category_code} belongs to both {existing} and {vertical_code}")
        mapping[category_code] = vertical_code
    return mapping


def _validate_catalog() -> None:
    vertical_code_list = [item[0] for item in VERTICALS]
    if len(vertical_code_list) != len(set(vertical_code_list)):
        raise ValueError("Duplicate vertical codes")
    category_code_list = [item[1] for item in CATEGORIES]
    if len(category_code_list) != len(set(category_code_list)):
        duplicates = sorted({code for code in category_code_list if category_code_list.count(code) > 1})
        raise ValueError(f"Duplicate category codes: {duplicates}")
    unknown = {item[0] for item in CATEGORIES} - set(vertical_code_list)
    if unknown:
        raise ValueError(f"Categories reference unknown verticals: {sorted(unknown)}")
    category_belongs_to_unique_vertical()


_validate_catalog()


def vertical_codes() -> list[str]:
    return [item[0] for item in VERTICALS]


def category_codes() -> list[str]:
    return [item[1] for item in CATEGORIES]


def vertical_by_code(code: str | None) -> tuple[str, str, str] | None:
    if not code:
        return None
    text = str(code).strip()
    return _VERTICAL_BY_CODE.get(text) or _VERTICAL_BY_CODE.get(text.upper())


def category_by_code(code: str | None) -> tuple[str, str, str, str] | None:
    if not code:
        return None
    text = str(code).strip()
    return _CATEGORY_BY_CODE.get(text) or _CATEGORY_BY_CODE.get(text.upper())


def resolve_category_code(value: str | None) -> str | None:
    if value is None:
        return None
    text = str(value).strip()
    if not text:
        return None
    if text in _CATEGORY_BY_CODE:
        return text
    if text in LEGACY_CATEGORY_MAP:
        return LEGACY_CATEGORY_MAP[text]
    upper = text.upper()
    if upper in _CATEGORY_BY_CODE:
        return upper
    return _LEGACY_CATEGORY_LOWER.get(text.lower())
