class ActorType:
    USER = "USER"
    ADMIN = "ADMIN"
    SYSTEM = "SYSTEM"
    API_CLIENT = "API_CLIENT"
    AI = "AI"


class EntityType:
    OFFER = "OFFER"


class OfferEventType:
    CREATED = "OFFER_CREATED"
    UPDATED = "OFFER_UPDATED"
    STATUS_CHANGED = "OFFER_STATUS_CHANGED"
    HOLD_CHANGED = "OFFER_HOLD_CHANGED"
    TRAFFIC_POLICY_CHANGED = "OFFER_TRAFFIC_POLICY_CHANGED"
    ACCESS_POLICY_CHANGED = "OFFER_ACCESS_POLICY_CHANGED"
    PRODUCT_CHANGED = "OFFER_PRODUCT_CHANGED"
