from enum import StrEnum


class NotificationType(StrEnum):
    SDK_CONNECTED = "SDK_CONNECTED"
    SDK_EVENTS_STOPPED = "SDK_EVENTS_STOPPED"
    POSTBACK_FAILED = "POSTBACK_FAILED"
    POSTBACK_HIGH_ERROR_RATE = "POSTBACK_HIGH_ERROR_RATE"
    SITE_DOMAIN_VERIFIED = "SITE_DOMAIN_VERIFIED"
    SITE_VERIFICATION_FAILED = "SITE_VERIFICATION_FAILED"
    PAYOUT_DUE = "PAYOUT_DUE"
    PAYOUT_REMINDER = "PAYOUT_REMINDER"
    PAYOUT_OVERDUE = "PAYOUT_OVERDUE"
    PARTNER_TRAFFIC_SUSPENDED = "PARTNER_TRAFFIC_SUSPENDED"


class NotificationSeverity(StrEnum):
    INFO = "INFO"
    SUCCESS = "SUCCESS"
    WARNING = "WARNING"
    CRITICAL = "CRITICAL"
