from __future__ import annotations

from enum import StrEnum


class GuidanceIntent(StrEnum):
    CHANGE_STYLE = "CHANGE_STYLE"
    CHANGE_TONE = "CHANGE_TONE"
    SHORTEN = "SHORTEN"
    EXPAND = "EXPAND"
    IMPROVE_CLARITY = "IMPROVE_CLARITY"
    IMPROVE_STRUCTURE = "IMPROVE_STRUCTURE"
    IMPROVE_MARKETING_LANGUAGE = "IMPROVE_MARKETING_LANGUAGE"
    REMOVE_REPETITION = "REMOVE_REPETITION"
    EMPHASIZE_VERIFIED_FACT = "EMPHASIZE_VERIFIED_FACT"
    CHANGE_FORMAT = "CHANGE_FORMAT"
    ADAPT_TO_CHANNEL = "ADAPT_TO_CHANNEL"
    TASK_OVERRIDE = "TASK_OVERRIDE"
    PROMPT_INJECTION = "PROMPT_INJECTION"
    SECRET_EXTRACTION = "SECRET_EXTRACTION"
    SYSTEM_PROMPT_EXTRACTION = "SYSTEM_PROMPT_EXTRACTION"
    ROLE_OVERRIDE = "ROLE_OVERRIDE"
    PROGRAMMING = "PROGRAMMING"
    CALCULATION = "CALCULATION"
    GENERAL_QA = "GENERAL_QA"
    ADD_UNVERIFIED_FACT = "ADD_UNVERIFIED_FACT"
    ADD_UNVERIFIED_NUMBER = "ADD_UNVERIFIED_NUMBER"
    ADD_UNVERIFIED_PRICE = "ADD_UNVERIFIED_PRICE"
    ADD_UNVERIFIED_DISCOUNT = "ADD_UNVERIFIED_DISCOUNT"
    ADD_UNVERIFIED_URL = "ADD_UNVERIFIED_URL"
    ADD_UNVERIFIED_ENTITY = "ADD_UNVERIFIED_ENTITY"
    ADD_UNVERIFIED_CLAIM = "ADD_UNVERIFIED_CLAIM"
    ADD_UNGROUNDED_CONTENT = "ADD_UNGROUNDED_CONTENT"


ALLOWED_EDITING_INTENTS = frozenset(
    {
        GuidanceIntent.CHANGE_STYLE,
        GuidanceIntent.CHANGE_TONE,
        GuidanceIntent.SHORTEN,
        GuidanceIntent.EXPAND,
        GuidanceIntent.IMPROVE_CLARITY,
        GuidanceIntent.IMPROVE_STRUCTURE,
        GuidanceIntent.IMPROVE_MARKETING_LANGUAGE,
        GuidanceIntent.REMOVE_REPETITION,
        GuidanceIntent.EMPHASIZE_VERIFIED_FACT,
        GuidanceIntent.CHANGE_FORMAT,
        GuidanceIntent.ADAPT_TO_CHANNEL,
    }
)

FORBIDDEN_DEFAULT_INTENTS = frozenset(
    {
        GuidanceIntent.TASK_OVERRIDE,
        GuidanceIntent.PROMPT_INJECTION,
        GuidanceIntent.SECRET_EXTRACTION,
        GuidanceIntent.SYSTEM_PROMPT_EXTRACTION,
        GuidanceIntent.ROLE_OVERRIDE,
        GuidanceIntent.PROGRAMMING,
        GuidanceIntent.CALCULATION,
        GuidanceIntent.GENERAL_QA,
        GuidanceIntent.ADD_UNVERIFIED_FACT,
        GuidanceIntent.ADD_UNVERIFIED_NUMBER,
        GuidanceIntent.ADD_UNVERIFIED_PRICE,
        GuidanceIntent.ADD_UNVERIFIED_DISCOUNT,
        GuidanceIntent.ADD_UNVERIFIED_URL,
        GuidanceIntent.ADD_UNVERIFIED_ENTITY,
        GuidanceIntent.ADD_UNVERIFIED_CLAIM,
        GuidanceIntent.ADD_UNGROUNDED_CONTENT,
    }
)
